### ISSUE TITLE
Add district type to model for frontend

### ISSUE THREAD

**Issue by jfrankl** [PublicMapping/districtbuilder#1005]
On the "My maps" page, we want to be able to show what type of districts are being drawn (State House, State Senate, Custom, etc.). This information is not currently available on the frontend.

**Comment by ktohalloran** [comment]
@jfrankl @maurizi Where are we picturing putting this information on the project card? I initially made it 

**New Jersey · 40 General Assembly districts** or **Delaware · 5 custom districts**

using `chamber.name` to fill in the type, as it doesn't look like there's a more general type like "State Senate" that each district is then mapped to; however, it looks like most names in chamber in production are very specific, like Florida Senate, Washington Legislative Districts, etc. Those situations look kind of funky in my initial plan, e.g.

**Alabama · 35 Alabama State Senate districts**

Another thought I had was doing 

**Alabama · 35 districts · Alabama State Senate**

What do you think of either of those? Or should I try to add some kind of logic that uses `chamber.name` to display a more general type like "State Senate" here?

**Comment by jfrankl** [comment]
Here is the relevant design on Figma: https://www.figma.com/file/FYobD6UsJZoNxlpyxUOlR5/Application?node-id=0%3A111

I think the state name should be first, but not sure if the type or number should go next. I think keeping the number and type separate, as opposed to combining them into a sentence, makes it slightly easier to scan, which is important for this page.

**Comment by ktohalloran** [comment]
Thanks @jfrankl. I can't view the Figma design--it says I don't have permission.

**Comment by ktohalloran** [comment]
I'm also realizing I may have misinterpreted the scope of this issue--is this card just about making info we already have in the backend accessible to the frontend for this purpose or does it include adding a generic `district_type` column to the chamber table?

**Comment by maurizi** [comment]
@ktohalloran the intent here isn't to add any new fields - we should just use the existing name field.

I think based on Jeff's wireframes, and given that the name for most state-level chambers starting w/ the state name, it would be best to do somthing like your third option:

Alabama · 35 districts · Alabama State Senate
