### ISSUE TITLE
Purchase AWS Savings Plan

### ISSUE THREAD

**Issue by colekettler** [PublicMapping/districtbuilder#1017]
In order to reduce the cost of our EC2 instances, we should purchase an AWS Savings Plan. We usually purchase reserved instances (RIs) for EC2 instances, but a Savings Plan is appealing in the event that we migrate back to Fargate. A Savings Plan will continue to apply to Fargate spend but RIs would not.

Because we're working on reducing our ECS cluster size in #1016 and other performance improvement issues, we may want to only cover a subset of our spend with a Savings Plan. We should determine how much we want to invest while considering our break-even point on investment, and how large we expect our application cluster to be at that point.

**Comment by BryanQuigley** [comment]
Compute savings plans are being purchases in our root payment account - for reference DB is recommended at about $0.393 an hour.
