### ISSUE TITLE
ECS scale-down alarm is stuck in "alarm" state

### ISSUE THREAD

**Issue by ddohler** [PublicMapping/districtbuilder#1093]
## Description
The alarm responsible for scaling down the EC2 instances in response to a decrease in the number of application service tasks is stuck in the alarm state.

The practical effect of this is that the number of desired tasks and the minimum number of desired ECS instances must _both_ be adjusted in order to change the number of active application service tasks, because the alarm will always scale down until the ASG's minimum size is hit, regardless of how many application service tasks we have specified. If we fix the alarm to take the number of CPUs available in the chosen ECS instance type into account, we should be able to adjust only the number of desired service tasks and let the alarm take care of the autoscaling.

## Steps To Reproduce
Visit the Cloudwatch console and view the "Alarms" section.

## Expected behavior
The alarm should trigger only when there is a mismatch between the number of provisioned instances and the number of application service tasks.

## Actual behavior
The alarm always triggers.

## Screenshots
<img width="839" alt="Screen Shot 2022-01-04 at 4 26 30 PM" src="https://user-images.githubusercontent.com/447977/148126341-8b4b781c-3e45-4176-aa32-6d12050633ce.png">

**Comment by BryanQuigley** [comment]
This doesn't seem to be an issue anymore - or at least it's not actively in-alarm.  close?
