### ISSUE TITLE
Explore options to improve application startup time

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#1117]
My testing for #960 revealed that the `deserialize` operation itself is not a significant cause of our slow startup time loading TopoJSON layers - suggesting that even in production, the time is predominately spent loading data from S3.

We should explore options for loading the assets from disk instead as a way to improve startup times (caching, a centralized EBS volume, storing the assets in the docker container?) as well as try to estimate how much time savings we would expect to see.

**Comment by BryanQuigley** [comment]
Speed was pretty reasonable from S3 but did vary a lot from 5 MiB to 20 at different times. 

I'm thinking three things could explain/speed it up:
 * Separate out downloading items from S3. Make it a separate program that runs before the main one. Then the main app loads it from disk as it's only option.
 * Compress the items on S3 - some items compress really well - input.geojson 231 MB -> 44 MB
 * Reduce number of small files in mutiple directories (or compress them as one tarball). (I just had this issue with another project, trying to copy individual files was going to take 2 hours, once compressed to 400 MB it took 1 minute)

**Comment by maurizi** [comment]
We actually don't load `input.geojson` on the server, or anything in the tile directory.

The files we're primarily concerned with for server load are the `.buf` files actually - `topo.buf` being the primary & very large one, plus a dozen or so much smaller `.buf` files.

**Comment by maurizi** [comment]
As Derek pointed out, my tests were done locally using a nice NVMe SSD, so we maybe can't expect 12 second load times out of EBS: https://github.com/PublicMapping/districtbuilder/pull/1128#discussion_r803746281

It's worth benchmarking EBS performance to see what we can expect.

Another option to consider is using local NVMe storage, and pre-loading the data into the AMI, which won't give us _instant_ load times (the docs say it can take up to 5 minutes to copy the AMI image to the machine), but would still likely be substantially faster than loading from S3, and could perhaps offer better performance in a cache-miss scenario than EBS.

**Comment by ddohler** [comment]
I'm hopeful that an EBS volume will be fast enough -- my recollection is that instances with local instance storage don't come with batteries included, so you have to mount the drives and format them yourself, which would add a lot of extra moving parts to AMI creation. But they are very fast once you get them up and connected to everything else.

**Comment by maurizi** [comment]
Knowing the performance of using EBS for our data caching will help us decide how to move forward on reducing application startup times.

Closing this, we'll re-assess load times after implementing #1138 (which will end up using instance storage, which is EBS-backed).
