### ISSUE TITLE
Signup page enhancements

### ISSUE THREAD

**Issue by dmcglone** [PublicMapping/districtbuilder#1123]
Add a checkbox (pre-checked) for newsletter signup. They should be added to the DistrictBuilder mailchimp audience.

Terms of Use link should link to https://www.azavea.com/terms-of-use/ until we finalize DistrictBuilder specific terms of use.

Design:
https://share.goabstract.com/c5af9126-cf61-41fa-8c41-765205ce7a70

**Comment by aaronxsu** [comment]
Discussed with @maurizi about the technical scope, and here is the game plan.

#### 0. Shared:
- Update `IUser` data model, add a field `readonly isMarketingEmailOn: boolean`
- Update `Register` data model, add a field `readonly isMarketingEmailOn: boolean`
#### 2. Backend:
- Add a field to the `User` entity: `isMarketingEmailOn`, type: `boolean`. Non-nullable. Default: false.
- Add a field to the `RegisterDto` entity: `isMarketingEmailOn`, boolean, not optional
- Create a migration using `migration:create` command, which takes an arg as the name of the migration
- This field should not be filtered out in returns, i.e. nothing specially needed in the service or controller
#### 3. Frontend
- Update the Auth component to reflect the design change, re: checkbox, copy, and T&C text
- Init value of this field in state should be `true`; add callback on change of the checkbox
