### ISSUE TITLE
Scheduled REINDEX rule not applied to production

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#1129]
The recent production release `1.14.0` included changes meant to run a REINDEX query on a monthly schedule (https://github.com/PublicMapping/districtbuilder/pull/1101).

However, the rule created on AWS only seems to apply to the staging site, and not production: https://console.aws.amazon.com/events/home?region=us-east-1#/eventbus/default/rules/reindex-scheduled-ecs-event-rule
![image](https://user-images.githubusercontent.com/4432106/153414719-41f72a3c-6832-41d4-b2e0-309ce65d39fb.png)

**Comment by maurizi** [comment]
I think the issue here is that were supposed to parameterize the rule name by environment? (i.e. `reindex-scheduled-ecs-event-rule-staging` / `reindex-scheduled-ecs-event-rule-prod`).

I'm not sure on that though.

**Comment by BryanQuigley** [comment]
Despite my PR.. I'm still going to look into pg_cron:
 * Needs pg_cron extension added to avavea postgis container
 * Might need terraform upgrade as I've found an open issue (https://github.com/hashicorp/terraform-provider-aws/issues/12025) - reproducing or confirming it's fixed might be a good first step
 * needs migration to actually set it up
