### ISSUE TITLE
Geounit selector

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#113]
Geounit drawing selector to choose from the available geounits

![image.png](https://images.zenhubusercontent.com/5d2f73297fbe250a8f844eb1/600c0751-62d7-4495-8022-c4087d3acf34)

**Comment by jfrankl** [comment]
This looks right, except we should add "blocks" as a third option.

I want to share a related enhancement. We could have a popover appear when a user selects "blocks", which would contain a message that says something about how blocks are more restricted and slower and try to suggest that people might want to use other geounits unless they really need blocks. I don't know the right way to word that, but it would make it clear that this is some pro-level stuff.

The user would have an option to "Enable blocks". If they do, then afterwards, the block selection button will work like normal. The idea is to add a little friction the first time, to make sure people want to use blocks enough to deal with the limitations.

![image](https://user-images.githubusercontent.com/1809908/83217278-5df88f80-a139-11ea-89d6-1d2059eea176.png)

@tgilcrest let me know what you think.

**Comment by kshepard** [comment]
Note: now that we have the ability to draw districts, this issue should also accommodate the ability to draw districts using multiple geolevels. Currently, only the top-most geolevel is able to be selected, so it's easy to perform an update to the district definition. Supporting multiple geolevels here will require a non-trivial amount of logic to allow appropriately updating the district definition.

**Comment by tgilcrest** [comment]
@jfrankl Didn't see your question at the end of the comment. I think that's a good suggestion, but I don't want to implement this right away. We should keep this in mind but wait to see if there seems to be a lot of confusion around Blocks. I would prefer doing something simpler for now like just graying-out the Blocks selection until the user zooms in far enough, at least for launch. Users who know what Blocks are will know where to find them, and inexperienced users won't be able to immediately get themselves into a confusing situation. How does that sound?

**Comment by jfrankl** [comment]
@tgilcrest that sounds good to me.

**Comment by kshepard** [comment]
@jfrankl reminded me of a discussion we had a long time ago, where we decided we were going to only allow selecting geounits from a single geolevel at a time. If another geolevel is chosen while a selection is active, we will automatically perform the `Approve` functionality. This will give us a much less complex path forward, as we will need to account for fewer tricky situations. It will be possible in the future to optimize the approach so this auto-approval is only the case when dealing with blocks (i.e. we can still allow combining counties/blockgroups at the same time), but putting this restriction in place across the board right now will make things a lot easier. I'm going to think through this issue, as well as the related issue #114 some more, and will likely close them and create a set of new issues that more clearly encapsulate everything we're looking to do.
