### ISSUE TITLE
Reduce database size and monitor performance

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#1139]
AC:
 - Reduce database size from `db.t3.large` to `db.t3.medium`
 - Reduce provisioned I/O
 - Monitor performance for several days and determine that no metered resources (CPU burst, I/O burst) are being depleted over time

**Comment by BryanQuigley** [comment]
> Reduce database size from db.t3.large to db.t3.medium
Scheduled for Tuesday at 3:30 am ET.

**Comment by BryanQuigley** [comment]
Updated terraform prod variables with instance type change

Enabled performance insights on both staging and production.
Reduced production IOPS from 1200 to 1000 (which may be minimum we can reduce it to right now

**Comment by BryanQuigley** [comment]
updated terraform prod variables. 1000 is as low as we can go without more substantial changes - like changing storage type.

**Comment by BryanQuigley** [comment]
(of note peformance monitoring I did not add to terraform, but it's something I may look at in future)
