### ISSUE TITLE
Limit block geounit visibility by zoom level

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#114]
- Only show blocks at a minimum zoom
- Zoom in if blocks are selected? Or just make them not selectable?
- Switch to blockgroups when zooming out past threshold
- Prevent zooming out if some blocks have been selected on the map

**Comment by jfrankl** [comment]
This is the direction I'd recommend for the start. If blocks are selected and the user is zoomed out to a level where we haven't generated blocks, we'd show a panel like this:

![image](https://user-images.githubusercontent.com/1809908/83217973-f8a59e00-a13a-11ea-913a-5d0f6979718e.png)

The user could manually zoom in or click the "zoom in" link to automatically zoom in to the level where we have blocks generated.

I think this will be easy to implement and also be easier to explain than automatically zooming or restricting zoom in certain conditions. This option informs the user and allows them to make their own choices, which I think makes sense for DB, especially this feature which is for more advanced users.

**Comment by jfrankl** [comment]
Just to make sure we're on the same page:

- If "County" is selected, we show county lines and users can click to select counties
- If "Block groups" is selected, we show county lines and block group lines, and users can click to select block groups
- If "Blocks" is selected, we show county lines, block group lines, and block lines (at a certain zoom level), and users can click to select blocks

**Comment by kshepard** [comment]
Note: now that we allow drawing districts, the ability to select districts should also be tied into this issue. Making this happen in the general case would mean that if a user selects geounits from a geolevel that isn't available at all zoom levels, then they are no longer allowed to zoom out to the point where that geolevel won't be visible.

So a user can select a county, select some block groups, zoom in and select some blocks, but would then not be allowed to zoom out past the point where blocks would no longer be visible. Note that we will likely need to have some metadata about zoom levels added to the metadata when processing GeoJSON, so it's available on the client-side.
