### ISSUE TITLE
Expandable metrics viewer

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#115]
[wireframe](https://app.abstract.com/projects/9f988240-1dad-11e8-9a40-cba930331af7/branches/master/commits/238ea75510f11bde6dcba5f841bd99aa326bd167/files/DCA38482-FC7F-4F48-BECD-44E07D9F7443/layers/C4E68FD7-B7C0-40D9-85B2-932B16FCE42B)
[wireframe 2](https://app.abstract.com/projects/9f988240-1dad-11e8-9a40-cba930331af7/branches/master/commits/09b392079f20d92a20fe38878b27420f0bd1e703/files/DCA38482-FC7F-4F48-BECD-44E07D9F7443/layers/917A65DA-42F8-45E1-AB95-F35E6E0A9E78?mode=design&sha=09b392079f20d92a20fe38878b27420f0bd1e703)
- Button on side bar expands to full screen
- Button on expanded version to contract back to sidebar
- Columns can be pinned to the sidebar to view
- Only a certain number of columns can be pinned
- Only certain columns can be pinned (some always show, District Color and Number, District population)

Note:
* Jeff would like to talk to the developer about this. The design is good, but implementation details need clarified.

**Comment by kevinearldenny** [comment]
@jfrankl A few outstanding questions I have here:

- Is this in the normal Project Sidebar? Or for the sidebar in Evaluate Mode?

- Can you clarify a bit further on what 'pinning' is? Seems like if this is for the normal Project Sidebar, it would be a way of defining the columns which are displayed when the expanded view is not displayed.

- Are these configurations specific to a project? Or is this a change that a user would make that would then apply to any project that they look at?
