### ISSUE TITLE
Reduce production EC2 capacity

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#1157]
Now that `1.15.0` has been deployed with both performance improvements and the dropping of archived layers, we should be able to both go down in instance size (we should only need 32GB of memory now) and number of instances.

AC:
 - Test reducing instance size on staging
 - Deploy new smaller instances on production
 - Gradually reduce number of production instances and watch performance metrics

**Comment by maurizi** [comment]
In terms of what instance to switch to - the natural choice is going down one size in our current class to `r5.xlarge`, but we should consider trying out `r6g.xlarge` (which uses ARM processors) instead, as it is 40% cheaper, and there's no reason to think it will affect our application; the only native binding in our server code is `bcrypt` which also has ARM bindings:
```shell
$ find node_modules -name '*.node'
node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node
```

**Comment by BryanQuigley** [comment]
For our instance types at least (at on-demand costs) ARM is only a 20% savings. Switching to AMD gets us 10% savings and we stay on x86_64 which seems good enough.

r5.xlarge	$0.252	4	32 GiB
r5a.xlarge	$0.226	4	32 GiB
r6g.xlarge	$0.2016	4	32 GiB

**Comment by BryanQuigley** [comment]
According the the cluster, staging is at 40% memory usage while production is at 49%

Production (1 at random) vs Staging
Mem used: 33220 vs 26469
Docker: 33.23GiB vs 25.15GiB

Leaving the instance type alone for now, but moving container_instance_app_desired_count from 6->4.

**Comment by ddohler** [comment]
It looks like the memory usage may be due to the LRU cache that we've added (either that or we've got ourselves a memory leak, but it looks like the slope levels off around 56%, so I'm inclined toward the former):
<img width="1168" alt="Screen Shot 2022-03-04 at 13 37 52" src="https://user-images.githubusercontent.com/447977/156822483-aaf70685-1d39-4634-adde-ac15accb4295.png">

There's a number we can tweak to control how much memory the cache is allowed to use, which I think is currently set at 80% of available memory. Given that we're so close I bet we could squish things a bit to fit within 32GB, but probably best to let @maurizi dig into it next week.

**Comment by maurizi** [comment]
@BryanQuigley I tried load testing staging using `r5a.xlarge` instances, and found they doubled the time it took to load a large state like TX or PA after a cache miss, to the point where it would often time out (e.g. a cache-miss for Texas is 12-15 seconds on `r5.2xlarge`, but more than 30 seconds on `r5a.xlarge`).

I'm deploying an `r6g.xlarge` to staging now and load testing it to see what performance we get from that instance type.

**Comment by maurizi** [comment]
I'm taking back my strong stance on the performance of the `r5a.2xlarge` - I need to retest with the _exact_ same load tests (I had been on a different commit when testing the `r5a.2xlarge` instances).

And simply switching the base image to `r6g.xlarge` doesn't work - trying to start the server immediately crashes, presumably because we're not pushing an ARM-based Docker image, so I'm holding off on further attempts to try that for now 😢

**Comment by maurizi** [comment]
Ok, back to report here with more accurate info re: `r5.2xlarge` vs `r5a.2xlarge`:

It's not actually _file load times_ (and thus cache-misses) that are slower on the `r5a.2xlarge`, but rather the TopoJSON merge operation is slower: taking ~5s on an `r5.2xlarge` and ~8-9s on `r5a.2xlarge` to edit the official PA state house map (my load test used lots of merge operations to trigger cache eveictions, so I was measuring both).

That's a much bigger perf. hit than I'd expect for only a 10% savings - I'm not sure if that's worth it.

**Comment by BryanQuigley** [comment]
r5a.2xlarge doesn't sound worth it for 10%. That sounds like we could call this issue done for now unless we want to try with just 1 ec2 instance (which actually might be fine)

**Comment by maurizi** [comment]
@BryanQuigley with the changes in #1172, once they're deployed I think we can try running using `r5.xlarge` - probably going from 2 `r5.2xlarge` to 3 `r5.xlarge` would be safest.
