### ISSUE TITLE
Upgrade PostgreSQL 13 in development and staging

### ISSUE THREAD

**Issue by aaronxsu** [PublicMapping/districtbuilder#1234]
The app currently is on PostgreSQL 12.4 with PostGIS 3. AWS marked this version as deprecated. 

We recently have had successful upgrades to version 13 for other projects/apps on staging and production. We should do the upgrades for this app too, which would have benefits of reducing the number of DB versions we maintain.

Similar to how we performed such an upgrades elsewhere, this issue covers the upgrades in development and staging environments.

**Comment by BryanQuigley** [comment]
Thinking it might make sense to just drop having a custom paramater group. Very similar to defaults and we are unlikely to optimize them?

log_autovacuum_min_duration | 250 | 10000
-- | -- | --
log_connections | 0 | engine-default - afaict off
log_disconnections | 0 | engine-default - afaict off
log_lock_waits | 1 | engine-default - afaict off
log_min_duration_statement | 500 | engine-default off/-1
log_temp_files | 500 | engine-default off/-1
random_page_cost | 1 | engine-default - 4 
seq_page_cost | 1 | engine-default - 1

**Comment by BryanQuigley** [comment]
Staging is upgraded.
Left it at the previous parameter's because that was actually easy to do with no terraform changes.  - Updated prod plan in #1235

May look at the page_cost bits later as that could be negatively impacting our performance.
