### ISSUE TITLE
Upgrade PostgreSQL 13 in production

### ISSUE THREAD

**Issue by aaronxsu** [PublicMapping/districtbuilder#1235]
Similar to what we did in other apps, after we have successful upgrades of PostgreSQL 13 and PostGIS 3.1 in development and staging, we should perform it on production.

**Comment by BryanQuigley** [comment]
- [ ] SELECT PostGIS_Extensions_Upgrade(); to get to 3.1.4 (run twice then log back in to confirm)
 - [ ] Change Terraform variables to 13 and 13-version parameter group
 - [ ] Run Terraform - will create new group and fail to change DB
 - [ ] Manually Update database from 12.8->13.6 - choosing the new parameter group terraform created
 - [ ] SELECT PostGIS_Extensions_Upgrade(); to get to 3.1.5 (run twice then log back in to confirm)
 - [ ] Maybe some [REINDEXing](https://adamj.eu/tech/2021/04/13/reindexing-all-tables-after-upgrading-to-postgresql-13/)? Not sure  it's worth doing a FULL VACUUM as it didn't do much last time. 
 - [ ] Run another terraform plan

Check commands to run before doing a long operation:
SELECT * FROM pg_available_extensions WHERE installed_version IS NOT NULL;
SELECT * FROM pg_available_extension_versions WHERE name in ('postgis', 'plpgsql');
\l+ (database sizes)

**Comment by aaronxsu** [comment]
Hey @BryanQuigley , regarding the following item:
>Maybe some [REINDEXing](https://adamj.eu/tech/2021/04/13/reindexing-all-tables-after-upgrading-to-postgresql-13/)? Not sure it's worth doing a FULL VACUUM as it didn't do much last time.

From the docs, it seems good to me that this `REINDEX ... CONCURRENTLY` is a non-blocking operation for write/update/delete. I also saw a sentence in the docs saying `Of course, the extra CPU, memory and I/O load imposed by the index rebuild may slow down other operations.` So I am wondering if there is any past experience from other similar projects (considering the tables, records, and indices on them) DB upgrades that could give us some idea of if we need to schedule an app downtime to perform it. Or, we could probably do [this issue](https://github.com/PublicMapping/districtbuilder/issues/1064) first and perform the reindexing on staging (prod replica). What do you think?

**Comment by BryanQuigley** [comment]
A full vacuum took 1.5 hours on DB prod (on psql 12 a few weeks ago), IMU this should take less time.  We have to schedule downtime for the DB upgrade itself anyway.

**Comment by aaronxsu** [comment]
@BryanQuigley sounds good.

Hey @maurizi, what would be our usual process for scheduling downtime? I am curious about the following:
1. Do we show a special login page or something similar that temporarily blocks frontend login during downtime?
2. Do we happen to have any heuristic of usual low usage time of the app or anything we could infer from CloudWatch to pick a date and time?

**Comment by maurizi** [comment]
> From the docs, it seems good to me that this REINDEX ... CONCURRENTLY is a non-blocking operation for write/update/delete. I also saw a sentence in the docs saying Of course, the extra CPU, memory and I/O load imposed by the index rebuild may slow down other operations. So I am wondering if there is any past experience from other similar projects (considering the tables, records, and indices on them) DB upgrades that could give us some idea of if we need to schedule an app downtime to perform it. 

We currently run `REINDEX ... CONCURRENTLY` for our largest table, `project`, on a monthly basis: https://github.com/PublicMapping/districtbuilder/pull/1101 at midnight Eastern time, and it hasn't caused any issues. From experience it can take quite some time (longer than an hour), but the application remains in a usable state while it's ongoing.

> Do we show a special login page or something similar that temporarily blocks frontend login during downtime?

@BryanQuigley whipped up something really basic for one very-long period of downtime recently, but nothing too fancy. Static assets are served by the backend, so if the application is down it's not possible to get to the login page itself.

> Do we happen to have any heuristic of usual low usage time of the app or anything we could infer from CloudWatch to pick a date and time?

Our busiest times tend to be evenings. In the past when we've had downtime we've scheduled it during business hours.

**Comment by BryanQuigley** [comment]
Tuesday isn't the best fit for me.. but tomorrow or Friday this week or Wed/Thursday next week work.

**Comment by BryanQuigley** [comment]
Also dropped unused extensions: address_standardizer_data_us, address_standardizer, postgis_raster

Performed some other DB OS updates during downtime.

Manually enabled Performance Insights on Prod DB.

All done and now on Postgres 13  - PostGIS 3.1.
