### ISSUE TITLE
Publicly shareable map URL

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#126]
- Generate a URL to the map that can be viewed anonymously, but not edited.

**Comment by jfrankl** [comment]
I propose that we add a "Share" button in the header. Clicking on that would open a dropdown, revealing a url that can be easily copied. For the copy to clipboard, I recommend using https://github.com/wsmd/use-clipboard-copy. If a developer can get the basic functionality in, I'd be glad to do a style pass.

![image](https://user-images.githubusercontent.com/1809908/92039036-60731280-ed42-11ea-859c-674736c40754.png)

![image](https://user-images.githubusercontent.com/1809908/92039048-679a2080-ed42-11ea-8c56-26934dcf4e80.png)
