### ISSUE TITLE
Anonymous app usage

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#127]
[wireframe](https://app.abstract.com/projects/9f988240-1dad-11e8-9a40-cba930331af7/branches/master/commits/e0cf02e79bd4ac07f05864ec2adba16c06c29948/files/DCA38482-FC7F-4F48-BECD-44E07D9F7443/layers/C2FD0807-F2D0-4302-AF12-82F18CA61B53)
- Can load home page without signing in
- Can create a project without signing in
- Can edit districts without signing in
- Prompt to sign in on first save

**Comment by dmcglone** [comment]
Closed, not doing. We want user to sign in before editing maps.
