### ISSUE TITLE
tslint -> eslint

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#128]
`tslint` is deprecated.

The recommended upgrade path is to convert the project to `eslint` (see https://github.com/typescript-eslint/tslint-to-eslint-config)

**Comment by tgilcrest** [comment]
How critical is doing this right now?

**Comment by kshepard** [comment]
> How critical is doing this right now?

Not immediately critical, it just happens to be a great first issue for someone to pick up.
