### ISSUE TITLE
504 Gateway Time-out on app.districtbuilder.org

### ISSUE THREAD

**Issue by tmgarner01** [PublicMapping/districtbuilder#1320]
## Description
504 Gateway Time-out on app.districtbuilder.org

## Steps To Reproduce
1. Go to app.districtbuilder.org
2. See error

## Expected behavior
Website loading normally

## Actual behavior
Plain white screen with the text: "504 Gateway Time-out".

## Screenshots
![image](https://github.com/PublicMapping/districtbuilder/assets/132721756/3e970817-f779-4d5d-ba4f-67bb7b556c13)

## Your environment

 - OS: Ubuntu  22.04.3 LTS
 - Browser: Firefox
 - Version: 120.0

**Comment by tmgarner01** [comment]
Whatever it was, it seems to be fixed now

**Comment by theeddiejones** [comment]
Hmmm, still seeing the same error today on the 29th...
![Screenshot from 2024-03-29 08-51-42](https://github.com/PublicMapping/districtbuilder/assets/95725040/971819f5-e7fb-4817-adf0-8b03bc0abe29)

**Comment by Famijos** [comment]
Still going on
