### ISSUE TITLE
Upgrade packages with security vulnerabilities

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#133]
## Overview
GitHub has identified several security vulnerabilities in packages that we are using. We should upgrade these packages.

## Details
I've listed the dependency files that were listed and the packages that are affected with links to the Advisory Database record:

* `yarn.lock`
  * [minimist](https://github.com/advisories/GHSA-vh95-rmgr-6w4m)
  * [kind-of](https://github.com/advisories/GHSA-6c8f-qphg-qjgp)
  * [acorn](https://github.com/advisories/GHSA-6chw-6frg-f759)
  * [serialize-javascript](https://github.com/advisories/GHSA-h9rv-jmmf-4pgx)
* `src/server/yarn.lock`
  * [minimist](https://github.com/advisories/GHSA-vh95-rmgr-6w4m)

## Notes
[class-transformer](https://github.com/advisories/GHSA-6gp3-h3jj-prx4) (in `src/server/yarn.lock`) was also listed but has no patched version listed. We should just try to avoid a situation where this could affect us?

**Comment by maurizi** [comment]
No need to worry about `class-transformer` so long as we're not using it directly: https://github.com/nestjs/nest/issues/4598#issuecomment-617171860

**Comment by maurizi** [comment]
This have been updated
