### ISSUE TITLE
Add region config & chamber database fixture for development use

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#137]
## Detailed Description
To enable getting started from a fresh installation, we should add a development database fixture (or script, or some other means of sharing data) to load DBs with region configs for already processed files stored on S3.

## Context
This will enable spinning up on the project more easily and enable simpler destruction/recreation of dev environments

## Alternatives
We could remove the region config from the database entirely, and store what is currently in the DB in a metadata file on S3 alongside the processed files.

**Comment by dmcglone** [comment]
We do this with load-dev-data
