### ISSUE TITLE
Refactor email transporter config

### ISSUE THREAD

**Issue by ColeKettler** [PublicMapping/districtbuilder#165]
## Detailed Description
#158 [includes](https://github.com/PublicMapping/districtbuilder/pull/158/files#diff-eaf879078595bdb90b902cf31d9a5b86L22-R23) the SES email transporter in addition to the local stream transporter.

The [way we're currently handling config](https://github.com/PublicMapping/districtbuilder/pull/158/files#diff-eaf879078595bdb90b902cf31d9a5b86R20-R34) could be improved. Ideally the caller should not have to worry about [which properties are present in the mail object](https://github.com/PublicMapping/districtbuilder/pull/158#discussion_r437721622) and there may be a more robust way to handle this sort of conditional config.

**Comment by tgilcrest** [comment]
@kshepard What's your opinion on this?

**Comment by ColeKettler** [comment]
I've been discussing this in #158. Ops would prefer preserving this functionality for sake of consistency with other projects but we're trying to figure out the best way to handle configuring it. We're likely to coordinate with DistrictBuilder developers in an upcoming sprint.

**Comment by kshepard** [comment]
I agree with the rationale here.

**Comment by ColeKettler** [comment]
We ended up preserving this functionality, though the solution could use some improvement. I'm queuing this up for our next sprint. Ops will coordinate with one of the DB devs to pair up and make the code pretty ✨ 

I've also updated the description to turn this issue into a refactoring issue.

**Comment by ColeKettler** [comment]
I paired up with @kshepard on this one. We figured out that this object we were logging was defined with an `any` type in an upstream module. We decided to refactor logging and property checking to a separate function to increase visibility of how we're handling the potentially different object properties.
