### ISSUE TITLE
Show toast message for errors on saving districts

### ISSUE THREAD

**Issue by kshepard** [PublicMapping/districtbuilder#188]
## Overview

There currently isn't a good place to notify users of errors that occur on the map page. When errors are returned from the server (for example, when saving districts), we need a place to show them. This will probably involve some design time, since it isn't currently clear where these errors should be displayed.

## Acceptance criteria

When an error is encountered while saving a map, display a toast message to the user "Something went wrong. Please try again."

**Comment by jfrankl** [comment]
I'm thinking a toast library, such as this, would be a good option for this need: https://github.com/fkhadra/react-toastify

**Comment by kshepard** [comment]
Reopening this to handle actually handling and displaying the errors.
