### ISSUE TITLE
Increase memory allocation for Fargate tasks to load TopoJSON for additional states

### ISSUE THREAD

**Issue by ColeKettler** [PublicMapping/districtbuilder#192]
## Overview

We established [an ADR](https://github.com/PublicMapping/districtbuilder/blob/fc3d86fb8a66ff823e4473a8a34c4561e447f8f8/doc/arch/adr-04-server-side-static-data-loading.md) in #184 to determine our approach for loading TopoJSON data in memory server-side. At this time, we are planning to launch with a subset of all 50 states, which will be increased over time.

To implement the decision in ADR-04, we need to:

- Increase the amount of memory available to each Fargate task to accomodate additional states
- Only declare the application healthy via health check once states are loaded into memory

### Notes

We have established 12 GiB as an upper bound for the amount of memory required. This is unlikely to be the actual required amount of memory, since that estimate assumed that all states were as complex as the most complex state, California. We can tune the scaling amount of allocation as we add states.

## Acceptance Criteria

Each Fargate task should be running with an amount of available memory that scales with the declared number of states to be loaded, and TopoJSON should be loaded before the application is declared healthy.

**Comment by hectcastro** [comment]
For the first pass, we are going to aim for a parameterized integer that multiplies some amount of RAM quantity per state.
