### ISSUE TITLE
Join organization

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#226]
We want to make it possible for users to "join" an organization so they can participate in the public mapping initiatives for the organization. This will also help the organization keep track of the users involved in mapping with their organization.

Note: this will require a new database table and associated migration.

AC:
1. There is a "Join organization" button on the organization page
2. When a user joins an organization there is a record that associates them with the organization. 
3. The button should change to indicate to the user they have joined the organization
4. After a user joins an organization there is an option to leave the organization
5. If the user is not logged, in the button is still active but when they click on it, they are prompted with a modal to signup / login to DistrictBuilder. This is the same modal we use for Copy Map
    - Note: The login modal for this action will need to have different text than that of Copy map. Final draft of text incoming.
6. The organization page reports how many "mappers" have joined that organization

[Link to wireframe before join](https://share.goabstract.com/dcdb1f2e-51e6-4d14-9900-b2eedb4f52f8?mode=design&sha=a2773927bab40c149b0241488dd07c1da51dbba5)
[Link to wireframe after join](https://share.goabstract.com/8e936976-246b-4ee6-b1b4-eaf521393c93?mode=design&sha=a2773927bab40c149b0241488dd07c1da51dbba5)

**Comment by kevinearldenny** [comment]
@tgilcrest From reviewing the wireframes, it seems like there isn't a button in the 'after join' wireframe that shows how the 'Leave Organization' button should look. This is the current state:

_pre-join_
![image](https://user-images.githubusercontent.com/66973361/108111420-a73f9500-7062-11eb-9f21-97f831fd6150.png)

_post-join_
![image](https://user-images.githubusercontent.com/66973361/108111472-b6264780-7062-11eb-8a03-6c9ed796546f.png)

Any thoughts on if this is acceptable?

**Comment by tgilcrest** [comment]
LGTM! I think if we want to do something fancier later @jfrankl can help think through that.
