### ISSUE TITLE
Create project from district template

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#228]
We support drawing a district map from scratch. Another common way users begin drawing districts is by creating a project from a template. Questions:
* Should this be an option in the standard creation workflow? Do we want to support this for (all/some) states?
* What data do we need to support this, what format, where/how should it be loaded?
* How would we do it and how much work would this take?
* Who could do this?
* How would this work with the Organization page? How would an Organization pick a template they want to feature?

**Comment by dmcglone** [comment]
We did it.
