### ISSUE TITLE
Increase max zoom level

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#231]
## Description
While testing the new drawing changes, I tried to zoom into blocks. I was able to zoom to the point where blocks appeared, but could zoom no further. We should make it possible to zoom in further so that users can work with block effectively. We want to make sure this is accessible for a wide range of users, like those who need larger shapes to make them discernible, so they need to be able to zoom far enough in so the smallest of blocks can be made large.

AC:
1. When a user switches to blocks, they are able to zoom far enough into the map so that all the blocks are clearly visible and can easily be selected with the pointer tool.

## Screenshots
This image demonstrates a significant range of block sizes. The blocks in the red box are too small to see and to work with. The blocks in the yellow box are just too small to work with, and the blocks in the green are comfortably sized. In fact, I would suggest we even let users go a bit larger. 

![image](https://user-images.githubusercontent.com/14098314/88812669-fe911d00-d185-11ea-91e7-34b84abb6fdc.png)

**Comment by jfrankl** [comment]
One point of clarification: we should increase the maxzoom across the entire project, regardless of what geounit you have selected. This will fix @tgilcrest's issue, but also reduce some awkwardness around having different maxzooms depending on your geounit selection (and be easier to build).

Note: increasing the maxzoom does not mean generating new tiles for the increased zoom levels. It is possible to zoom past where you have tiles, and Mapbox GL JS can [overzoom](https://docs.mapbox.com/help/glossary/overzoom/).
