### ISSUE TITLE
Rectangle tool acts like invisible single select

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#236]
## Description

When the rectangle tool is selected, it is possible to use it like the single select tool to select geounits individually. The problem, however, is that the geounit does not look like it is selected. 

## Steps To Reproduce

1. Go to a map
2. Select the rectangle tool
3. Click on a geounit

## Actual behavior

The geounit does not appear to be selected because it is not colored gray. However, the population updates in the sidebar and the Accept/Reject buttons appear, indicating that something has been selected. Clicking Accept will add the geounit to the selected district, confirming that it had been selected.

## Expected behavior

This should do one of two things. Either:
1. The geounit turns gray indicating it is selected
2. The geounit is not selected (it does not turn gray, Accept/Reject do not appear, and no changes are show in the sidebar)

I have a preference for 1. We expect the geounit to be selected as soon as the user moves the mouse. For the average user with a mouse or a trackpad, they are unlikely to be clicking without moving the mouse slightly (they may not even be able to). So the difference between a click and click+drag is minimal and we should treat them as the same action.

## Screenshots

I have the rectangle tool selected and clicked on the geounit in the red box. The Accept/Reject buttons appear and the sidebar updates, but the geounit is not highlighted.

![image.png](https://images.zenhubusercontent.com/5d2f73297fbe250a8f844eb1/f6ded335-5159-4b98-97bc-ef8caf410553)

## Your environment

 - OS: Windows
 - Browser: Happens in both Chrome and Firefox

**Comment by jfrankl** [comment]
I don't have a strong sense for which option would work better. Option 1 seems good to me.
