### ISSUE TITLE
Only show lines for selected geolevel

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#241]
Currently we show lines for every geolevel on the map (subject to allowed zoom level). This can be confusing when drawing because you expect to draw with the shapes you can see. However, the shapes you see aren't always the same as the geolevel you have selected, so it's easy to think you will select blockgroups when you actually have counties selected. Because of this, we should only show lines for the selected geolevel on the map (edit: and higher geolevels; so, if you have blockgroups selected, you should see blockgroups and counties).

**Comment by jfrankl** [comment]
Slight change on this @tgilcrest. We should show lines for the selected geolevel and any level above it. So, if you have blockgroups selected, you should see blockgroups and counties. If you have blocks selected, you should see blocks, blockgroups, and counties.

We can use different styling on each to make it more clear which is which when multiple are on the screen.
