### ISSUE TITLE
Improve UX for zooming with restricted geolevels

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#245]
## Description

We prevent selecting the blocks geolevel at zoom levels below a certain threshold. However, if you zoom in, select the blocks geolevel, and then zoom out, blocks are still selected but they are grayed out and we don't clearly explain what changed and what a user needs to do to continue working with blocks. The user can't select geounits on the map until they manually select an available geolevel. For example:

![prevented-selection.gif](https://images.zenhubusercontent.com/5d2f73297fbe250a8f844eb1/7ee81f47-b7d4-445e-b389-9d397814086a)

To remedy this, we want to make it more clear that the user needs to zoom back in to see and interact with blocks by showing a them a message (see screenshot). We also want to not gray-out the blocks geolevel so it's clear the blocks geolevel is still active.

AC:
1. When a user selects a restricted geolevel (i.e. Blocks) and zooms out past the min-zoom, we show a message that explains: `Zoom in to work with [geolevel]`. (See screenshot)
2. Also when this happens, the blocks geolevel button is still active and indicates blocks are still selected (rather than being grayed out).
3. When zoomed out, if a user selects a non-restricted geolevel  the restricted geolevel button is deactivated and returns to a state like in #268 / #287. 
4. If a user has a restricted geounit selected, the user can zoom out past the min-zoom (rather than be limited to it) and the selection is maintained (i.e. sidebar shows proposed change, if you zoom back in the selection is still there)

## Screenshots

![image](https://user-images.githubusercontent.com/14098314/90571966-edce3880-e180-11ea-80f4-7c9e5daf4e4c.png)

**Comment by jfrankl** [comment]
I edited this issue to reflect the new direction mentioned in this message: https://github.com/PublicMapping/districtbuilder/pull/270#issuecomment-669479824

**Comment by tgilcrest** [comment]
Updated to capture the various nuances.

**Comment by tgilcrest** [comment]
@jfrankl What do you think of `Zoom in to work with blocks`? It's a little more concise than `Zoom in to view and select blocks`.

**Comment by jfrankl** [comment]
@tgilcrest looks good to me.
