### ISSUE TITLE
Create tooltip component

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#265]
Currently we just use the title text in some places as tooltips. We should create an actual tooltip component that we can use in place of the title text.

Places:
* Block geounit switch button when disabled
* Polsby-Popper Compactness
* Non-contiguous
* Race chart

Tooltip requirements:
* Smart positioning: will avoid rendering off screen
* Has the ability to add a delay, of variable time, before tooltip opens

**Comment by jfrankl** [comment]
Requirement for a tooltip library: it should be smart enough to automatically position the tooltip in view.

![image](https://user-images.githubusercontent.com/1809908/89461631-3bd34d00-d73a-11ea-9f07-87a69e894021.png)
