### ISSUE TITLE
Make transition between non-zoom-level-limited geounits seamless

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#267]
Currently, if a user has an active geounit selection and switches the geolevel, we automatically accept the changes in the selection. This automatic accepting can be unexpected and frustrating. In the prototype, the user can select geounits on one level and switch to another level and continue selecting geounits, without needing to Accept/Reject changes. We should emulate that interaction.

The one wrinkle is the full version in block support. In order to visualize blocks, we've had to implement zoom level limitations so we don't overload the browser. So we have two types of geolevels: 1) loaded and visible at every zoom level, and 2) only loaded at a limited set of zoom levels. 

We should implement seamless district drawing for geolevels in 1), because they'll always be available. We expect geolevels that fall under 2) will be for more advanced, so we'll create some more friction to get to them, and don't need this same seamlessness/fluidity.

AC:
1. For zoom levels in 1), users can select geounits in any geolevel and then switch to a different level and continue selecting units. The selection will stay in progress and will not be automatically accepted/rejected.
2. When a user accepts the selection, all the selected geounits of all levels are added to the district
3. Rejecting the selection will clear all selected geounits

Note: The interaction for geolevels in 2) will change, but will be handled by a separate issue.

**Comment by jfrankl** [comment]
Here are some related mockups: https://share.goabstract.com/0446558a-4a08-43dc-8103-695ff2360f46
