### ISSUE TITLE
Style pass: map tooltip

### ISSUE THREAD

**Issue by jfrankl** [PublicMapping/districtbuilder#279]
### Description
Style cleanup on the map tooltip. The design in the mockup is slimmer. It's important for this component to maintain a small footprint so it doesn't cover too much of the map.

### Design assets

- Tooltip: https://share.goabstract.com/5691f15f-619c-4426-b48d-8835ca32c8f3?mode=design&sha=a408aeb9a005792b7061a451337c3a93a62c95c9

### Notes
Ignore the content highlighted in this image. We don't have that in the tooltip yet.
![image](https://user-images.githubusercontent.com/1809908/89683858-4f5fee80-d8c7-11ea-985d-ad460ef08819.png)

**Comment by tgilcrest** [comment]
The tooltip is displaying behavior where it stays visible when you mouse off the map:

1. Zoom the map in so geo-units line the top edge of the map
2. Mouse over a geo-unit on the top edge of the map so the tooltip shows up
![image.png](https://images.zenhubusercontent.com/5d2f73297fbe250a8f844eb1/dbbaec03-f111-47a9-8091-0a9efa3d04e7)
3. Move the mouse up off the map
4. The tooltip flickers and stays visible, but it should disappear

Can you fix this as part of this issue? Or should I add it to #374 for a developer to grab?

**Comment by jfrankl** [comment]
@tgilcrest could you have a developer do that? I think it's more in their wheel house, but I'm happy to support.

Maybe related, I am finding the tooltip dancing around when I'm close to the edge of the screen to be annoying. I am thinking of removing the functionality that tries to position it based on cursor position.
