### ISSUE TITLE
Use county name as label in map tooltip

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#281]
The DA team is adding county name to the demographic data file. We should update the label on the cursor tooltip to show `[county name] County` instead of `County #n`.

### Screenshots
Current tooltip:
![image.png](https://images.zenhubusercontent.com/5d2f73297fbe250a8f844eb1/ba5d73d1-37bf-44bd-bea4-377aa023a908)

Prototype:
![image.png](https://images.zenhubusercontent.com/5d2f73297fbe250a8f844eb1/8d5806df-fc5b-4254-9a04-b588f065cd1c)

**Comment by maurizi** [comment]
Needs a little more tweaking to account for City-Counties:
![image](https://user-images.githubusercontent.com/4432106/91225430-9cc6c300-e6f1-11ea-9cd3-c49a5fe572ee.png)

**Comment by tgilcrest** [comment]
Per Wikipedia, these are [Independent Cities](https://en.wikipedia.org/wiki/Independent_city_(United_States)) and most of them are in VA:
>Of the 41 independent U.S. cities,[1] 38 are in Virginia, whose state constitution makes them a special case. The three independent cities outside Virginia are Baltimore, Maryland; St. Louis, Missouri; and Carson City, Nevada. The most populous of them is Baltimore, Maryland.

I checked the data we get from the data pipeline for all 41 of these independent cities and they all contain ` city` in them, even in the case of St. Louis and Baltimore whose neighboring counties share the city name: `St. Louis city`/`St. Louis` (county), `Baltimore city`/`Baltimore` (county). So in all cases, when there is ` city` in the label we should convert it to title case and should not append county.
