### ISSUE TITLE
Unassigned geounits with zero population

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#297]
Some unassigned geounits may have zero population. We should make sure to account for this when calling a map "complete", meaning we should not call a map complete until all population _and_ all geounits are assigned to a district; we shouldn't just rely on zero unassigned population.

We don't have a concept of "complete" maps yet, but will need to account for this when we do.

**Comment by dmcglone** [comment]
Our concept of complete is no geounits left unassigned.
