### ISSUE TITLE
Remove confirm password field

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#312]
We don't have a message that tells you when your "confirm password" entry doesn't match, so it can be confusing if you misspell one of them and it won't let you register. We should remove the confirm password field since you can reset your password if you mis-type it and sometimes these fields can mess with password managers. This is a also pattern more sites are starting to adopt.

**Comment by jfrankl** [comment]
One more note in addition to what @tgilcrest wrote. The "Let's go" button should never be disabled, because that prevents the user from seeing validation messages.
