### ISSUE TITLE
Disable Accept for locked districts

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#314]
Consider doing this if we get feedback from users about "lock" being confusing.

Currently, if a user selects geounits while they have a locked district selected, they can add those geounits to the locked district. This may be confusing to users if they think lock means no operations are allowed to a district. A possible way to handle this is to disable the Accept button when a user has staged changes on a locked district (with a tooltip saying to unlock the district to accept changes).

**Comment by dmcglone** [comment]
Not going to do, have not heard from users this is an issue
