### ISSUE TITLE
Add link and style "Thanks for registering" page

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#321]

**Comment by jfrankl** [comment]
When a user confirms their email address, they are sent to an unstyled page. This page should contain: 

- The DistrictBuilder logo
- Some text
- A link/button back into the application
- Optional: an icon or graphic, potentially borrowed from the marketing website, that makes this page feel slightly more rewarding

![image](https://user-images.githubusercontent.com/1809908/90806673-589b8300-e2eb-11ea-8290-552f4171c7d3.png)
