### ISSUE TITLE
Migrate districtbuilder.org hosted zone to Route 53

### ISSUE THREAD

**Issue by hectcastro** [PublicMapping/districtbuilder#326]
Ensure that all of the DNS records in GoDaddy are migrated to Route 53, then update the `districtbuilder.org` name server configuration on GoDaddy to delegate to Route 53.

This will likely require Terraform state manipulation for both the production and staging AWS accounts.

**Comment by rbreslow** [comment]
In addition, we should update the `r53_public_hosted_zone` variable to reflect the new domain in both staging and production.

**Comment by ColeKettler** [comment]
@hectcastro Nameservers have been switched over in GoDaddy DNS management to point to the nameservers in our districtbuilder.org hosted zone. Everything looks to be functioning as expected.

I've also removed the districtbuilder.azavea.com hosted zone from Terraform state, manually deleted and Terraform-managed records, and retained the pa.districtbuilder.azavea.com NS records.

This is ready for review.

**Comment by hectcastro** [comment]
Everything looks good. I think both versions of DB are functioning as expected with the update domains, and the DTL site is still working well. 👍
