### ISSUE TITLE
Update warning modal copy

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#384]
Update:
>Block Editing is our most advanced editing mode, which enables the most accurate redistricting possible. It is used to fine-tune your districts when your map is nearly complete (e.g. to achieve zero population deviation). Block Editing is only recommended for experienced users who are comfortable navigating around the map and drawing controls.
>
>**Limitations of Block Editing**
> * Blocks are only visible when you zoom in. If you zoom out too far, the blocks will be hidden (but don't worry, they'll still be there for you when you zoom back in!)
> * If you select some blocks, you will need to resolve pending changes (click Accept or Reject) before you can leave Block Editing.

**Comment by jfrankl** [comment]
What do you think of changing "If you select some blocks" to "Once you select one or more blocks". I think "some blocks" has a slight ambiguity in that it could also mean that some blocks require you resolve changes, while others do not.

**Comment by tgilcrest** [comment]
I agree with that. How about:
>Once you start selecting blocks...

which I think is a little tighter.
