### ISSUE TITLE
Ignore unexceptional Rollbar errors

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#388]
A number of "errors" are being reported to Rollbar that are normal & expected:
 - Failing healthchecks as the service loads
 - DB constraint errors checking for duplicate users

We should ensure these expected errors are filtered before being reported, and audit the application for any other errors that should be ignored.

**Comment by pcaisse** [comment]
Another example: https://rollbar.com/Azavea/DistrictBuilder/items/24/?utm_campaign=new_item_message&utm_medium=slack&utm_source=rollbar-notification

**Comment by hectcastro** [comment]
> We should ensure these expected errors are filtered before being reported...

I think this is the intent of the sentence above, but just to be clear, I think we need to make sure that filtering occurs _before_ exceptions are reported to Rollbar vs. between Rollbar and Slack. Not sending exceptions to Rollbar that we expect to filter will help preserve our account quotas.

**Comment by ColeKettler** [comment]
The Rollbar filter added in #338 is registered as the global uncaught exception filter. Any other exception filters will catch the exception and handle it it before it bubbles up to the Rollbar filter. The [`BadRequestExceptionFilter`](https://github.com/PublicMapping/districtbuilder/blob/develop/src/server/src/common/bad-request-exception.filter.ts) global filter is an example of this in action. This may be able to serve as a basis for handling other categories of exceptions.
