### ISSUE TITLE
Persist Locked Districts

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#405]
We don't persist locked districts so when you refresh the locked districts disappear. We should persist the locked districts so if you refresh or come back to your map later, we still maintain if they were locked. Save the locked district to the database and show the spinner when we make the call.

**Comment by jfrankl** [comment]
@tgilcrest We might want to consider persisting some other aspects as well. A few that come to mind:

- Selected geounits
- Map position
- Population label
- Selected district

**Comment by tgilcrest** [comment]
I think those would be good to consider. However I think they should be done separately for a couple of reasons:
- The length of persistence for those state-related items is shorter than I think it needs to be for locking. It's useful to keep those consistent on a session basis, whereas it would be useful to keep locking consistent on a project-basis. Besides just preventing edits, locking is a way for the user to indicate the district is "done" so they can mentally move on from it. That kind of progress marker should be kept on a project-basis so you don't lose your place if you start a new session later. Therefore, we want to save this in the database vs. in local storage so the implementation will be different.
- @kshepard mentioned there's some complexity to the ones you suggested that we should talk through before we tackle them

**Comment by jfrankl** [comment]
@tgilcrest makes sense to me.

**Comment by tgilcrest** [comment]
Should we show locked state to read-only view?

**Comment by jfrankl** [comment]
@tgilcrest on our call, there was consensus that "no" we should not show locked state in read-only view.

**Comment by pcaisse** [comment]
While backend support for this was added in #484, the frontend piece is dependent on reworking undo/redo since we would like to make it so that undo/redo history is retrained farther back than your last save (see #489). As such, we opted to hold off on this until that work is completed since it will be affected by it.

**Comment by tgilcrest** [comment]
@pcaisse After doing some testing on staging, the undo/redo changes in #498 work great, but it doesn't seem that the lock status of a district is persisted. Locking a district and refreshing the page clears the locked state from the district.

**Comment by pcaisse** [comment]
@tgilcrest Yup, I think I just referenced the wrong issue number. Good catch!
