### ISSUE TITLE
Fix `redux-loop`-related `console.error`

### ISSUE THREAD

**Issue by kshepard** [PublicMapping/districtbuilder#41]
## Description

There's a `redux-loop`-related `console.error` when running front-end tests.

## Steps To Reproduce

Run `./scripts/test`

## Expected behavior

Tests should complete successfully with no `console.error` messages.

## Actual behavior

```
$ react-scripts test --testPathIgnorePatterns=src/server --watchAll=false
 PASS  src/client/App.test.tsx (9.477s)
  ✓ renders without crashing (30ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        13.496s
Ran all test suites.
  console.error node_modules/redux-loop/lib/cmd.js:74
    connect ECONNREFUSED 127.0.0.1:80
```

## Your environment

Ubuntu 18.04, also seen on MacOS

**Comment by pcaisse** [comment]
In case it helps, this might require mocking something for `redux-loop` here: https://github.com/PublicMapping/district-builder-2/blob/develop/src/setupTests.ts

**Comment by dmcglone** [comment]
Fixed
