### ISSUE TITLE
Tooltip gets stuck on fast rectangle selections

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#411]
## Description

When selecting geo-units with the rectangle tool, it's possible to get the tooltip into a stuck state where it shows "X [geo-units]" all the time and only can get unstuck on certain actions.

## Steps To Reproduce

1. Go to a map
2. Select rectangle tool
3. Select an area, moving the mouse far and fast enough so it ends up outside the selected area after you make the selection

## Expected behavior

The tooltip continues to give you information about whatever you hover over.

## Actual behavior

The tooltip gets stuck showing however many counties you selected, wherever you go (see screenshot). Cancelling the selection or changing the drawing tool does not unstick it. The only way I've discovered how to unstick it (besides refreshing the page) is by drawing a rectangle slowly, and ending up inside the shape you're drawing. I've included a couple of gifs of the difference below.

My hypothesis is this is happening because of a slight delay between the when the tooltip shows, e.g., `21 counties` and when 
it shows `Prince Edward County`. If you are able to get the cursor off of the selection before it changes to `Prince Edward County` then the tooltip becomes stuck. It seems that only repeating this action but instead staying within the selection is the only way to reset it.

A side-effect of the tooltip getting stuck means it no longer disappears on hover away, as Kenny fixed in #408. 

## Screenshots

![image](https://user-images.githubusercontent.com/14098314/92979710-847cd500-f461-11ea-81aa-ad6c55059ff6.png)

Gif of two scenarios:
![stuck-tooltip](https://user-images.githubusercontent.com/14098314/92980087-cbb79580-f462-11ea-998f-0c946bd694b7.gif)

## Your environment

 - OS: Windows
 - Browser: Chrome
 - Version: 85.0

This also happened to Daniel; not sure if he runs the same setup.

**Comment by pcaisse** [comment]
@tgilcrest Are you still able to reproduce this? I'm not able to and I'm wondering if https://github.com/PublicMapping/districtbuilder/pull/452 fixed this issue. 

Here's me trying to reproduce it locally with NY data:
![db_tooltip_bug_cant_reproduce.gif](https://images.zenhubusercontent.com/5a036e618a75884b9086a55c/7522400c-098c-4959-b42e-501d5de3b942)

**Comment by tgilcrest** [comment]
I'm not able to reproduce it anymore. So seems to be fixed. 🤞
