### ISSUE TITLE
Confusing population labels

### ISSUE THREAD

**Issue by jfrankl** [PublicMapping/districtbuilder#419]
## Description
The population label for Putnam County in New York is `1.0e+2k`. I'm not sure why this is happening.

## Steps To Reproduce
- Create a New York project
- Turn on population labels

## Screenshots
![Screen Shot 2020-09-14 at 2 46 09 PM](https://user-images.githubusercontent.com/1809908/93126310-2be44c80-f69a-11ea-9dae-26ef17ef354c.png)

**Comment by kshepard** [comment]
Some brief troubleshooting. Values 99500 through 99999 are exhibiting this error
```
> value = 99500
99500
> suffixNum = Math.floor(Math.log10(value) / 3);
1
> abbrevNum = value / Math.pow(1000, suffixNum);
99.5
> Math.log10(abbrevNum)
1.9978230807457256
> abbrevNum.toPrecision(2) // Here is where the error occurs in the function
'1.0e+2'
> abbrevNum.toPrecision(3)  // It seems a precision of 3 should actually be used in this case
'99.5'
```

**Comment by kshepard** [comment]
Maybe we'll never encounter numbers so large, but just wanted to point out that it also happens for the next 10's place up:
```
> abbreviateNumber(999500)
'1.00e+3k'
```

**Comment by jfrankl** [comment]
@kshepard I think we can expect to see numbers that high at the county level.
