### ISSUE TITLE
Show majority minority districts

### ISSUE THREAD

**Issue by jfrankl** [PublicMapping/districtbuilder#426]
Add an indication that a user has drawn a majority-minority district.

* When a MM district has been created, there is a dotted line alongside the race demographic graph
* Hovering over the race graph pulls up the popup as it does now
* For MM districts there is a footer on the tooltip that indicates it's a MM district

![image.png](https://images.zenhubusercontent.com/5d2f73297fbe250a8f844eb1/6c659140-648d-46ca-9d18-dbe0cb0d9ab0)

![image.png](https://images.zenhubusercontent.com/5d2f73297fbe250a8f844eb1/5625df0d-01e9-407f-aa59-e75d91b6c420)

**Comment by jfrankl** [comment]
@tgilcrest could you add your mockup to this issue?

**Comment by tgilcrest** [comment]
![image](https://user-images.githubusercontent.com/14098314/93259229-813d5e00-f76d-11ea-9bcb-a9ab35e5bfb4.png)

**Comment by alexelash** [comment]
@tgilcrest designs for this are located here: https://share.goabstract.com/29b3f2a6-1ffb-4008-8b8a-815ce2ad90d1

A dashed line appears to the left of the chart when it a majority-minority. The hover tooltip also indicates this status.

fyi @jfrankl

**Comment by tgilcrest** [comment]
@alexelash I went to the link and don't see any designs in that collection yet. Could you update with the designs and let us know when it's ready?

**Comment by alexelash** [comment]
@tgilcrest Oddly, I just went in and see the designs there. Can you try the same link again?

**Comment by jfrankl** [comment]
I see them now, and I couldn't before. I'm guessing Abstract hadn't finished syncing with the server.

**Comment by alexelash** [comment]
Ugh, the worst! Yeah, that was my suspicion. It was the last thing I did before signing off so it must not have finished doing that. Glad it's up now at least.

**Comment by stephwall** [comment]
@maurizi follow up discussion needed.
