### ISSUE TITLE
Add details to map list

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#427]
As a user accumulates maps, it would be useful to have some additional details shown for each map in the list. Currently this is just a list but we should make it a table to hold the additional details:

![image.png](https://images.zenhubusercontent.com/5d2f73297fbe250a8f844eb1/b7c3d4c1-e6ea-48f1-b9e1-b48ac1ee3247)

AC:
* Convert map list into table
* Map table contains details:
  * Name
  * State
  * Chamber
  * Last edited

**Comment by tgilcrest** [comment]
@kshepard Is all of this information available on the page already or does it need more work to get the necessary info?

**Comment by kshepard** [comment]
On projects, we aren't currently storing the chamber that was used to create it, only the number of districts. We also don't have a last edited column, only created.
