### ISSUE TITLE
Use key to pan with rectangle and paintbrush tool

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#429]
To make it easier to pan the map when using the rectangle tool, we should set up a key press that toggles a panning control.

AC:
* When the rectangle or paintbrush tool is active, when the user presses the space key, the controls change the cursor to map panning.
* When the space key is pressed, the cursor changes to `grab` (see comment below)

A note on the complexity of the interaction of clicking and pressing space:
* Do nothing if the spacebar is pressed while the cursor is held. That means, wait until the user lets go of the cursor and then activate the grab hand. Until they let go of mouse button, the rectangle (and paintbrush for that matter) continue to function as they did before the spacebar is pressed.

Check out the comments below for more detail.

**Comment by jfrankl** [comment]
This would be great. I'd prefer to use the spacebar to do this function, which is a common pattern in every design tool. Shift already has a function in Mapbox GL and other mapping tools (shift zoom), so I think we should avoid that key in particular.

![image](https://user-images.githubusercontent.com/1809908/93475883-23bd2480-f8c7-11ea-87fd-af720d96959f.png)&nbsp;It's also important for the cursor to change to `grab` while you have shift down. 

The prototype has this for the paint brush tool, in case you want to check it out.

**Comment by tgilcrest** [comment]
@jfrankl a question came up in RRP about how this should work if the user hits space while clicking down with the rectangle tool. The prototype doesn't cover this case because the rectangle works slightly differently from the paintbrush.

A user may want to move the map while they are making a rectangle selection, so they can continue making the same selection past the edge of the map. What happens if they hit the space key in the middle of holding down the mouse button?

- Does it deactivate the tool and clear the selection? 
- Does it hold the selection in place where they pressed space until they release it?
- Or does it follow their cursor as they pan with space?

As I write this, I'm wondering if we should just do nothing if the spacebar is pressed while the cursor is held. That means, wait until the user lets go of the cursor and then activate the `grab` hand. Until they let go of mouse button, the rectangle (and paintbrush for that matter) continue to function as they did before the spacebar is pressed. 

If we want to handle the panning-while-selecting case, we implement the "edge proximity pan" we discussed a while ago.

**Comment by jfrankl** [comment]
> As I write this, I'm wondering if we should just do nothing if the spacebar is pressed while the cursor is held. That means, wait until the user lets go of the cursor and then activate the grab hand. Until they let go of mouse button, the rectangle (and paintbrush for that matter) continue to function as they did before the spacebar is pressed.

Let's go with this approach. It is easier to implement than allowing to draw and pan simultaneously. Ideally, we'd allow the user to draw and pan simultaneously, but for resource allocation purposes I think we should save that for a future enhancement.
