### ISSUE TITLE
Map tooltip is misplaced when dragging map on Firefox

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#451]
## Description
![779d63a5-c43a-4cb8-8b75-654ca4e52fa7](https://user-images.githubusercontent.com/4432106/94452092-28ae8d80-017d-11eb-8747-5b585115a5fa.gif)

## Your environment
 - OS: Windows
 - Browser firefox
 - Version 81

**Comment by pcaisse** [comment]
I believe this is a duplicate of https://github.com/PublicMapping/districtbuilder/issues/342

**Comment by maurizi** [comment]
Indeed
