### ISSUE TITLE
Shareable map changes

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#455]
After testing the first version of the shareable map, we want to make the following changes to improve it:

1. Remove ability to select districts (keep the cursor tooltip)
2. Remove the point and rectangle selection buttons
3. Remove the ability to lock districts 
4. Remove the Support and Share buttons
5. Remove block warning modal for view-only maps
6. Add byline (`by [Author Name]`)
7. Add text `Made with DistrictBuilder` that links out to https://districtbuilder.org

Mockup:
(ignore "Fork this Map" for now)
![image.png](https://images.zenhubusercontent.com/5d2f73297fbe250a8f844eb1/342c08b6-501d-448a-b954-4dbe17acdb2f)

Current page:
![image.png](https://images.zenhubusercontent.com/5d2f73297fbe250a8f844eb1/c161bf99-80c0-42ef-b43f-2dc45ce45bdd)

**Comment by kshepard** [comment]
Remember also to re-add the share menu that was temporarily removed in #465
