### ISSUE TITLE
Undo/Redo loses district geojson

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#473]
## Description
 - Make some changes
 - Accept the changes
 - Make a few more
 - Undo all the way back
 - Redo all the way back

There will be a step in the undo/redo stack for accepting the geometries but then the district geojson is not actually updated

## Steps To Reproduce

![1a54f0f4-365b-4029-9f12-378352c074dc](https://user-images.githubusercontent.com/4432106/96024237-784db400-0e21-11eb-9b61-75e6705b72f9.gif)

**Comment by tgilcrest** [comment]
This is resolved by the changes in #498.
