### ISSUE TITLE
The product tour should account for states with different geolevels

### ISSUE THREAD

**Issue by alexelash** [PublicMapping/districtbuilder#475]
Right now, all of the uploaded states have counties, blockgroups, and blocks. When we add a state that does not have these geolevels, we will need to update the product tour's hard-coded references to all three.

For example:
<img width="896" alt="Screen Shot 2020-10-15 at 3 58 09 PM" src="https://user-images.githubusercontent.com/5672295/96147462-427efd00-0eff-11eb-951d-b9ed0a73b2d1.png">

**Comment by kshepard** [comment]
Tentatively assigning myself to this, since I'm working on something related, and may implement it along the way.
