### ISSUE TITLE
Design population label and choropleth controls

### ISSUE THREAD

**Issue by jfrankl** [PublicMapping/districtbuilder#477]
## Detailed Description
Currently, we have a label dropdown that allows users to view labels on the map showing total population and also numbers by race. We have heard that the total population labels are very useful, while the race labels are not useful. For race, the number is less important than the proportion. A better way to communicate this information would be a choropleth, proportional symbols, or another visualization (#237).

## Context
When a builder is trying to reach a specific population goal, they want to know which geounits in their area of interest have the needed population. If they need 45 people to reach zero deviation, they want to easily find a block that has 45 people, or close. They will toggle labels on and off with regularity, to be able to see the city/POI labels more clearly.

When a builder is working on a majority-minority district, it would be helpful, at a glance, to be able to see what parts of the map have a higher proportion of that demographic.

## Possible implementation

Because the population label is toggled with regularity, it would be ideal if there were a way to toggle it with a single click, without needing to go into a more complicated menu.

**Comment by jfrankl** [comment]
We should also have an option for the demographic layer that would be "Non-white".

**Comment by alexelash** [comment]
Designs located here! https://share.goabstract.com/09034d14-15e5-4ccb-8dbd-8d246f4a079c

**Comment by tgilcrest** [comment]
Thanks Alex and Jeff!

So looking at the designs, it seems like it won't be possible to view a circle viz for total population, just the different populations by race? I would have assumed this would be possible.

**Comment by alexelash** [comment]
@tgilcrest could you clarify what you mean by “circle viz for total population”?

**Comment by tgilcrest** [comment]
Sorry that was vague. What I was trying to say was that the designs allow you to see number labels for the total population, but not the circle layer for total population, like you can see for each race population.

I talked to Jeff about it, and there's a couple things missing from the design that he wanted to take back and think about.

**Comment by alexelash** [comment]
Gotcha! I'll talk to Jeff about it -- thanks!

**Comment by alexelash** [comment]
@tgilcrest @jfrankl Revised designs that account for this additional toggle and some other considerationos are here: https://share.goabstract.com/2adad107-47ec-40dc-85f7-d02fb64befbe

**Comment by dmcglone** [comment]
We have designs
