### ISSUE TITLE
Make undo/redo work for all changes in a session (not just up until saving)

### ISSUE THREAD

**Issue by pcaisse** [PublicMapping/districtbuilder#489]
## Detailed Description
Currently undo/redo remembers selections only up until a save, meaning that once you save you can no longer undo your changes. Users don't seem to like this and want to be able to go back to previous states before a save. 

## Acceptance Criteria
* Users can go backwards and forwards between all previous states for that session up to a max of 100 states

**Comment by tgilcrest** [comment]
It seems this can be closed now that #498 is merged.
