### ISSUE TITLE
Copy Map as Template

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#493]
If a user is viewing a map (either a shared map or their own), we want to enable them to copy the map as a template and start a new map from it. This will create a copy of the map in the user's account so they can begin editing the map.

AC:
* There is a button on maps for "Copy Map"
* A modal pops up with a field to enter the new name of the map
* When the user confirms the name, the map is copied to the users account and the user is redirected to begin editing the map
* If the user is not authenticated, the modal instead prompts them to register with Name, Email, Password.
* If the user registers, we display a success message with Toast and the modal to copy map

**Comment by tgilcrest** [comment]
@jfrankl I drafted up a description of the "Copy map" functionality that we want to show on a shared map. Can you provide feedback on the proposed flow?

**Comment by jfrankl** [comment]
Hey Tyler, I made some screens for how I think this copy map feature should work: https://share.goabstract.com/87e194f6-21ab-41d0-baa3-3f746f6d2318?sha=9f9574b284f324d668d1ccb69d69089b42c31fd7

> There is a button on maps for "Copy Map"

I have a slight preference for "Copy this map"

> A modal pops up with a field to enter the new name of the map

A modal should appear, but it should explain what it means to copy a map and confirm that a user wants to do that. For the name, the project should receive a default name that matches the original name, but a user could change it.

> When the user confirms the name, the map is copied to the users account and the user is redirected to begin editing the map

Again, we won't ask 

> If the user is not authenticated, the modal instead prompts them to register with Name, Email, Password.

In this case, a user would see a different modal that explains why they need to register to continue. We'd also use this in other parts of the application where a user needs to authenticate to proceed.

> If the user registers, we display a success message with Toast and the modal to copy map

Yes, sounds good.

**Comment by tgilcrest** [comment]
Great, thanks for thinking through all that.

>In this case, a user would see a different modal that explains why they need to register to continue.
What happens when the user clicks "Create a free account" or "Log in"? Does it take them to the registration/login page and redirect them? Or does the modal contain the registration/login fields?
