### ISSUE TITLE
Configure Data for Maryland

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#511]
Load and configure the demographic data for Maryland.

US House of Representatives: 8 districts
Maryland Senate: 47 districts
Maryland House of Delegates: 47 districts

**Comment by MarcusAlzona** [comment]
Per https://github.com/PublicMapping/db-roadmap/issues/54 - how might @ryangniadek and I help with this @tgilcrest ?  Thank you!
