### ISSUE TITLE
Create incident report for 1.2.0 release outage

### ISSUE THREAD

**Issue by rbreslow** [PublicMapping/districtbuilder#514]
**Kenny’s notes:**

Deploy timeline:
- Deployed + kicked off migrations as soon as possible
- Everything instantly came up, even though there were errors related to migrations (speculating)
- Migrations succeeded
- I killed the tasks
- Things were coming up now, but were cycling
- My first thought was that the health check grace period wasn't high enough
- I upped the grace period and cycled instances
- Same thing happened, and now I noticed the 137 memory error
- Increased memory in terraform and restarted
- Same thing happened
- Noticed the memory was capped at 8GB
- Upped the vcpu setting to allow increasing the cap
- Restarted and everything came up successfully

**Rocky’s notes:**

- Release pipeline finished, tasks came up but no states loaded and CPU/memory utilization hovered around 0
- Ran migrations, killed the tasks to get it to cycle, then it’s coming back up
- First thought was that health check grace period wasn’t high enough, 400 -> 800, cycle again
- It should take 20min to come up now and it’s cycling after 8-9min, so clearly there’s something else going on
- Tasks are exiting due to out of memory error
- State count bump, should be plenty of memory, but it’s capped at 8GB
- Production vCPUs (1024) was lower than staging vCPUs (2048)
- Bump production vCPUs to 2048, memory formula is able to give the correct amount of memory for 20 states

Two issues:
- We added a field to the region config object with the migration. Without that field, is there an uncaught exception that zombifies the process? We should make things fail hard in the future, so the tasks can cycle on their own until migrations are ran.
- Formulate vCPU value based on state count.

**Comment by kshepard** [comment]
I added #515 to address the first issue here

**Comment by kshepard** [comment]
Wrote up an incident report here:

https://docs.google.com/document/d/1ghWFEFj2fiPscA2-KM8wscghWmfldO3EqO8HIamapCk/
