### ISSUE TITLE
Find shapes button and menu location

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#522]
The way Find Unassigned was implemented, the button is on the right but the pop-down is on the left. In the wireframe the pop-down was underneath the find button. That was an oversight, and now it's less obvious that something happens when you hit Find because it pops down away from the button.

This brings up the question of how it should be fixed. Should we move the pop-down underneath the button? (and what do we do with the zoom buttons?)

Or, should we instead move the Find button down, somewhere near the drawing buttons? Having the pop-down over there makes it easier to switch between the pop-down and the drawing tools that you use to fix the unassigned areas. Also, the Find button could make sense down there since it could be considered a "drawing-level" action, rather than a "project-level" action like the others.  If we move it down we'd need to redesign the button though to fit.

Current implementation
![image.png](https://images.zenhubusercontent.com/5d2f73297fbe250a8f844eb1/54f20b53-9892-4294-ad19-9a82d8fc42ea)

Wireframe
![image.png](https://images.zenhubusercontent.com/5d2f73297fbe250a8f844eb1/54e6418f-9d5a-4f7b-89a8-26ec9865a1d3)

**Comment by jfrankl** [comment]
Here are designs for this enhancement:

1. Move the zoom controls to the top left
2. Move the "Find" button from the top header to the map header, to the right of the label selection, separated with a vertical rule
3. When active, the button uses the same active color as the geounit and selection button groups
![A01](https://user-images.githubusercontent.com/1809908/100282190-2aa48b00-2f39-11eb-8d79-ef51f5a87009.png)
![A02](https://user-images.githubusercontent.com/1809908/100282191-2b3d2180-2f39-11eb-92e0-425f304dd731.png)
