### ISSUE TITLE
Add map thumbnails to list pages

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#537]
We want to show a thumbnail image for maps when we show them in a list. This will allow the user to see a little preview of the map while viewing several maps in a list.

[Wireframe example here](https://share.goabstract.com/83fab95f-28de-4c44-a198-0ab24f264bde?mode=design&sha=68b1a95c454910cae885dc67df3ee53436123795)

Note: This will likely involve figuring out how/when the thumbnails are refreshed. We probably don't want to do it on every map save, so do we need to run updates asynchronously and on some kind of schedule?

AC:
* When viewing the map list on the user's map list page, each row contains a thumbnail of the map
* When viewing the map list on the user's profile page (#535), each row contains a thumbnail of the map
* These thumbnails show a relatively recent version of the map (doesn't have to be immediate, but ideally it's never out of date by more than a day)

**Comment by dmcglone** [comment]
We did this.
