### ISSUE TITLE
Change CTA on State Dropdown

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#549]
We get a bunch of requests for new states in our email. I think this because we ask users to let us know when creating a map:

![image.png](https://images.zenhubusercontent.com/5d2f73297fbe250a8f844eb1/3466e285-90ff-40c3-b638-2f47dd3efa32)

Rather than send us an email, we should instead have people sign up for the mailing list so they know when new states (and features) will be released. So we should change this text and also update the mailing list sign up to capture additional info:

1. Update the text on the state dropdown to say (something like this--open to suggestions):
>What state do you want to map? If you don’t see it in the list, [sign up for our mailing list](districtbuilder.us1.list-manage.com/subscribe?u=61da999c9897859f1c1fff262&id=70fdf1ae35) to know when new states are available!
2. Add a new field to our [mailing list signup](https://districtbuilder.us1.list-manage.com/subscribe?u=61da999c9897859f1c1fff262&id=70fdf1ae35) to capture additional info (free text):
>What state do you want to map, or what feature is especially important to you?

I'm not sure where this would be captured exactly because I'm not sure how the mailchimp form works, but it would be great to capture this info somewhere as we build our list.

**Comment by alexelash** [comment]
@tgilcrest Re: mailchimp, there's a text limit for the field label, and we can't add a `textarea`, just a one-line`text` field. I suggest keeping the field scoped to missing states. How does [this look?](https://districtbuilder.us1.list-manage.com/subscribe?u=61da999c9897859f1c1fff262&id=70fdf1ae35)

<img width="1222" alt="Screen Shot 2021-01-11 at 1 03 40 PM" src="https://user-images.githubusercontent.com/5672295/104162135-7a69e380-540d-11eb-9109-14b0ebdc4cb6.png">
