### ISSUE TITLE
Add instructions for launching a frontend that talks with a staging backend

### ISSUE THREAD

**Issue by rbreslow** [PublicMapping/districtbuilder#55]
Once the staging environment is up, make sure there are instructions for launching a frontend that talks with the staging backend:

This would look something like:

```bash
DB_BASE_URL="" \
    docker-compose up client
```

This is a workaround to #43.

**Comment by hectcastro** [comment]
Blocked by https://github.com/PublicMapping/district-builder-2/issues/71.
