### ISSUE TITLE
Add Organization featured map administrator workflow

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#566]
Organization administrators need to be able to see all maps created from one of their organization templates, and to choose which ones to feature on their organization home screen.

![db-featured](https://user-images.githubusercontent.com/1809908/107421887-84eccb00-6ae8-11eb-809a-81eeff8d2ac5.png)

AC
 - There is a new endpoint which returns a list of projects connected to an organization via its project template(s)
 - There is a new endpoint which returns a list of featured projects for an organization
 - A new `admin` FK field is added to `Organization`
 - New models/migrations to handle the above
 - Support for updating Organization admin is added to the `update-organization` management command
 - Organization administrators have a screen [see above wireframe] where they can view all projects for their organization, and set which ones are featured (access to this should be blocked for other users)

**Comment by tgilcrest** [comment]
@jfrankl There aren't column headers in the wireframe above. The columns are probably self-explanatory, but do you think they would be helpful for sorting?

**Comment by jfrankl** [comment]
@tgilcrest Good catch. The designs and the application have diverged around the initial map list screen where you view a list of your maps. I just updated the mockup in the issue to reflect the current state of the map list view.

The differences between the Builder map list view and the Organization map list views:

- "Feature" button instead of the "..." button
- Breadcrumb "Fair Districts 2021 >"
- Brief description "Published maps that were created ..."
- Featured maps counter in the footer

**Comment by tgilcrest** [comment]
Thanks Jeff. I'm thinking Sort, Filter, Search, or Pagination could be important on this page at some point. If so, do you think it would make sense to update the list component to offer those on both this page and the My Maps page? (though true pagination might require backend changes).

**Comment by jfrankl** [comment]
Pagination and either filter or search seem like they'd be useful on both views. I'm less certain about the need for sorting, I'd want to hear more about that.

I'd also love to add the visual representation / screenshot of the districts to these views, which I'm hoping might be in reach if we implement this for the Featured Maps section of the Organization page.

**Comment by tgilcrest** [comment]
I was just thinking if an organization received 1000s of maps and thought it might be tedious to look through the whole list to find maps, but that can probably be pretty well covered by a CSV export to slice/dice and then ctrl-F once you know what you're looking for.

**Comment by kevinearldenny** [comment]
@maurizi @jfrankl Is there any distinction between different templates? It seems like it would be helpful for an admin to have the projects grouped based on which template they were created from, particularly in the scenario discussed above (1000s of projects for an organization), if there were projects created with multiple different templates it

**Comment by jfrankl** [comment]
@kevinearldenny good point. Instead of displaying the state name and number of districts, let's show the Template Name.

**Comment by jfrankl** [comment]
Here's where I want this page to get once we are able to generate thumbnails. ![image](https://user-images.githubusercontent.com/1809908/109534714-9f7fe780-7a89-11eb-9109-792d26275b6d.png)

**Comment by kevinearldenny** [comment]
@jfrankl Hmmm, I think what I'm getting at here is that there is an intrinsic hierarchy here:

- An organization can have multiple project templates
- Each project template can have multiple different projects created from it, by different users within the organization

So, to clarify my questions a bit here:

1. Do we want to group projects by template? I was thinking that it might make sense to have the projects associated with each of an organization's project templates displayed within collapsible lists grouped by template

2. Currently, there is no mention of who the user who originally created the project from an organization's template in the provided wireframe. Is this deliberate? It seems like this may be helpful to allow admins between different projects, in the event that there are a lot of projects associated with a template

**Comment by jfrankl** [comment]
1.) Good point, it would probably be useful to allow the user to organize by template. At the same time, there is a value in being able to view by map creation date. My thought is that by default we would order by map creation date, but there would be a way to filter by template name. What do you think of something like that, or did you have a particular solution in mind? We want to go with an easier-to-implement option if possible.
2.) Good catch, we should add the user who created the project. I will update the wireframes, but for now, just add another line with the creator's name with a mailto:[name] link so the organization can get in touch with the users.

**Comment by kevinearldenny** [comment]
So right now the data structure being returned has all of the projects nested underneath their respective project templates. It would be marginally easier (and perhaps make sense semantically) to have something like:

- Delaware - 21 districts (3 projects)
      - Jeff's DE map (3/1/2021)
      - Kevin's DE map (2/24/2021)
      - Mikes DE map (2/21/2021)

- Pennsylvania - 18 districts (2 projects)
    - Kevin's PA map (3/1/2021)
    - Mike's PA map (2/16/2021)

I do like your idea of having perhaps a separate view for this, with a toggle button for switching between the the 'by template' view and the 'order by recently updated' view. To me, it seems like having the projects grouped together in the 'by template' view (as exemplified above) may be a bit easier to work with than building out a 'filter by template' functionality - curious to hear @tgilcrest 's thoughts here on this

**Comment by jfrankl** [comment]
@kevinearldenny here is what I'm thinking for the table. I'd recommend [this React library](https://react-table.tanstack.com/), but feel free to pick a different one as long as it has sorting and pagination.

![Screen Shot 2021-03-02 at 3 15 38 PM](https://user-images.githubusercontent.com/1809908/109709575-ad596980-7b6a-11eb-842f-b2a4ab1b91f6.png)
