### ISSUE TITLE
Add verify and join org link to verification email

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#586]
When users create an account after trying to join an organization, we should keep track of that and make them automatically join the organization after verifying their email address.

Unlike when normally signing up, users should land on the organization homepage instead of the main districtbuilder homepage.

**Comment by kevinearldenny** [comment]
> Unlike when normally signing up, users should land on the organization homepage instead of the main districtbuilder homepage.

@tgilcrest @jfrankl  Is this before or after they confirm their email? 

If _before_ confirming email - 👍 

If _after_ confirming email - might it make sense to somehow instead add a link / box to link to organizations on the current 'Create a Map' homepage? 
![image](https://user-images.githubusercontent.com/66973361/110180252-7045df00-7dd7-11eb-8b01-b489547e0ec8.png)

Just for reference - the current flow on develop appears as this:

1) After clicking the confirm link in their email, they are currently directed here:
![image](https://user-images.githubusercontent.com/66973361/110180394-b0a55d00-7dd7-11eb-9a34-02b63d40dcfa.png)

2) And then after clicking login, they are just directed to a normal login screen
![image](https://user-images.githubusercontent.com/66973361/110180523-f3673500-7dd7-11eb-9f8f-506988462106.png)

3) -> This is the step we're discussing here. It seems somewhat nontrivial to implement a tracking of "is this a user who joined from an organization page's first login", so just wanted to confirm that you felt this was definitely necessary. 

If that is important to capture, it seems that this may be better implemented through a more general "Is this a user's first visit?" functionality with an alternative view for a user who joined from an organization - or by adding some sort of element to the homepage to allow for easy access to organization(s) that the user is a part of.

**Comment by tgilcrest** [comment]
>just wanted to confirm that you felt this was definitely necessary.

I linked you our Slack conversation where we discussed why we think this is important. Because we want users to be logged in and verified to join an organization, there are several steps a user brand new to DistrictBuilder has to go through to actually join an org (Sign up, go to email verify, go back to the org page and join). We're trying to make things easier for the user by putting them back on the org page.

The idea of this was to make it easier for a user to get right back to the org page they were trying to join after they verify their email. 

>If that is important to capture, it seems that this may be better implemented through a more general "Is this a user's first visit?" functionality with an alternative view for a user who joined from an organization

I'm not clear on the difference between this and the suggested idea, but happy to consider other approaches to make the implementation more straightforward. Could you elaborate?

>or by adding some sort of element to the homepage to allow for easy access to organization(s) that the user is a part of.

This is planned in #589. However, I don't think this will help in this case, as the user will not be allowed to join an organization prior to verifying their email address (and thus the org they were intending to join won't be in the list). The user will have to either have the org URL handy or go back to their original tab and refresh the page to join the org. This feature was to streamline this process.
