### ISSUE TITLE
Add configurable project poulation deviation

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#599]
AC:
 - New `deviation` numeric field to `Project` defaulting to `5`
 - Option to set `deviation` added to Create Project Screen, defaulting to 5

**Comment by jfrankl** [comment]
Here is a rough mockup of what it should look like. Please use existing styling (should look like the existing "new map" cards)![image](https://user-images.githubusercontent.com/1809908/112886506-05b75480-90a0-11eb-9d12-582e9e8518b4.png)
