### ISSUE TITLE
Add option to edit project population deviation

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#600]
AC:
 - Update the flyout menu shown on projects created from templates to also show an option for Population Threshold.
 - Choosing the above option should open a modal allow for editing project population deviation
 - Update the flyout menu to be shown for every project (not just those from templates)

**Comment by dmcglone** [comment]
@maurizi I think Map Configuration Modal #1025 will take care of this, feel free to close if so
