### ISSUE TITLE
Evaluate page map styling changes

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#604]
![image](https://user-images.githubusercontent.com/4432106/109849621-9294fc80-7c1f-11eb-8a98-176466286795.png)

AC
 - A new district numbers layer should be added and shown when in evaluate mode
 - Map styling matches wireframes, including all acceptance criteria in the note on the left (zoom, opacity, no labels)
 - If there are currently selected geounits they should not be styled differently
 - Leaving evaluate mode should restore map state (reshow selected geounits, labels, reset opacity, etc.)

**Comment by kevinearldenny** [comment]
@maurizi @jfrankl @tgilcrest Would it make sense to add some level of interactivity on the Districts layer here?

As I've been working on some of the other issues as part of the Project Evaluate feature, I'm noticing that the lack of interactivity on the map is a little less than satisfying. A couple of possible ideas I had:

a) A hover-selection type thing where hovering over a district in the table highlights it in the map, and vice versa

and then either:

b) A tooltip on the district layer with stats similar to what we have in the regular project view
c) A "detail view" for a district, where the map zooms in to the extent of the district and the sidebar display is filled in with detailed demographics and stats about the district, like
- Demographics
- Compactness
- Sq. miles
- Population density
- Counties included
- Competitiveness / historical election results

**Comment by jfrankl** [comment]
@kevinearldenny great idea. Let me make a quick mockup.

**Comment by maurizi** [comment]
@jfrankl and I discussed this - he's going to work on some new wireframes and we'll add interactivity to the map in a follow-on issue
