### ISSUE TITLE
Evaluate mode county split

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#608]
![image](https://user-images.githubusercontent.com/4432106/109851496-bce7b980-7c21-11eb-939f-55334c3f255e.png)

Notes:
We should try and be generic here instead of hardcoding county - so this can be "Ward split" mode for Dane County.

AC:
 - Update evaluate mode summary sidebar to display county splits. This should be possible to determine by seeing if the `districtsDefinition` has a `number` or `array` type at the top-most (county) level.
 - Show county split layer, map legend, and sidebar legend when switching to county split detail

**Comment by kevinearldenny** [comment]
@jfrankl I see that it appears there is a blank basemap here - was this intentional?

**Comment by jfrankl** [comment]
@kevinearldenny what's the easiest option? If it's to use the existing DB basemap, let's do that.
