### ISSUE TITLE
Create ECS management tasks through CLI

### ISSUE THREAD

**Issue by colekettler** [PublicMapping/districtbuilder#61]
#46 primarily covers documenting steps to start up ECS management tasks (e.g. migrations) through the AWS Console. We should develop a way to do this via a CLI-based tool using the Node AWS SDKs, like the approach used in [`django-ecs-manage`](https://github.com/azavea/django-ecsmanage).

**Comment by BryanQuigley** [comment]
Closing as we have moved to the SSM to EC2 container setup
