### ISSUE TITLE
Blocks editing limit

### ISSUE THREAD

**Issue by Jesse210** [PublicMapping/districtbuilder#618]
## Description

I've been using Block-level editing to fine-tune a map on the State House level.  With 203 districts though, I have done a lot of Block-by-block editing.  I hit a snag last week. Whenever I try to edit by Blocks on any District where I have not yet done so, I now get an error message ("Something went wrong, please try again").  As far as I can tell, I still have the ability to edit by Blocks on Districts where I already did so - but new ones are off limits.  If I eliminate previous Block edits, I am able to create new ones.  This leads me to wonder if there's there a limit on Block editing, or if this is a bug?

**Comment by tgilcrest** [comment]
@Jesse210 thanks for pointing this out. This sounds like a bug, and I'd like to test it out to see for myself. Could you provide the share link to the map where you saw this happening? 

If you'd rather not share on GitHub you can feel free to email me at tgilcrest@azavea.com.
