### ISSUE TITLE
Import Plan block equivalency CSV

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#627]
Wireframes:
![image](https://user-images.githubusercontent.com/4432106/111214444-5317ca00-85a8-11eb-8d43-7779959c616b.png)

![image](https://user-images.githubusercontent.com/4432106/111214469-590dab00-85a8-11eb-931f-f6c80e8097e5.png)

![image](https://user-images.githubusercontent.com/4432106/111214512-63c84000-85a8-11eb-8492-78a2214b580a.png)

![image](https://user-images.githubusercontent.com/4432106/111214573-780c3d00-85a8-11eb-977b-01217b105759.png)

Notes:

 - The file is a 2 column CSV, the first of which contains the full FIPS code for the block, with the 2nd column containing the district ID (or 0 for unassigned). Any blocks not in the CSV should also be placed in the unassigned district.
 - This is only a first-pass of this screen, and some features present in the wireframes will be tackled in later issues.
 - The part we're missing on the frontend for converting from block equivalency to `districtsDefinition` is a mapping of block index <->block FIPS code - if we built out an endpoint / additional static file for this, we would be able to implement the rest client-side - though that might require additional complications such as moving code into a web worker, so it probably makes sense to just stick to the backend.

AC:
 - Support uploading CSVs either through drag/drop or a file explorer window
   - Support uploading a new file to cancel/reset/undo
 - Auto-detect the region by looking at the first 2 digits of the FIPS code of the first row
 - Convert from block equivalency to `districtsDefinition`.
   - This piece likely needs to be implemented at least partially on the backend (we currently support the reverse, creating a block equivalency file, on the [backend](https://github.com/PublicMapping/districtbuilder/blob/develop/src/server/src/projects/controllers/projects.controller.ts#L355-L405) ).
   - When converting to `districtsDefinition` we should make sure to simplify beyond the block level where possible (e.g. all blocks in a blockgroup are in the same district, all blockgroups in a country are in the same district). See the end of this function for an example of this cleanup: https://github.com/PublicMapping/districtbuilder/blob/e4a49654f5c8ddb1c9818f2ec6e574fd11a6004a/src/client/functions.ts#L41-L76
 - Only custom chamber w/ explicitly provided # of districts needs to be supported for now, skip selecting a chamber
 - Skip the target population field for now
 - No extensive validation should be done in this issue - focus on the happy path of correctly formatted files.

**Comment by wboykinm** [comment]
@maurizi @ddohler Was this superseded or dropped?

Plan import of _some_ kind would be extremely valuable.

**Comment by maurizi** [comment]
@wboykinm It has been implemented!

You can create a new Plan by importing a block assignment CSV, by clicking on the "Import" button on the home screen, next to the "New map" button.

**Comment by wboykinm** [comment]
@maurizi That's fabulous! Thank you!
