### ISSUE TITLE
Error/warning validation modals for import plan

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#629]
# Wireframes
![image](https://user-images.githubusercontent.com/4432106/111311303-6d978500-8634-11eb-825a-13cfcc5466cb.png)
![image](https://user-images.githubusercontent.com/4432106/111311359-83a54580-8634-11eb-9edc-4509b037a0f2.png)

# Notes
We're very likely to need the modal with row-level details for any warnings/flags, but as per the first wireframe, it might not make sense for all or even any errors (they might be more top-level things like an invalid file format). You'll likely need to work with @jfrankl to clean up the details on this piece once the full set of conditions we're validating against is better known.

TG Edit: Like the note says, we should not create a modal for any errors, since we should just fail on the first one. Show something like this displaying the first error that we throw:
![image](https://user-images.githubusercontent.com/14098314/114880334-f9393880-9dcf-11eb-974f-d9976068793c.png)

# AC
 - Add row-level validation for the following warnings/flags:
   - unknown FIPS codes
   - duplicate FIPS codes
   - FIPS codes from more than 1 state in the same file
    - invalid district values
 - Add any file-level validations for errors that make sense (invalid file format, file too large, empty file, etc.)
 - If there are any errors, display them and allow the user to submit a different file
 - If there are flags, display the # of them in a link that will open a modal with details for each flag.

**Comment by tgilcrest** [comment]
We implemented this in DB Classic also. It may be helpful to review the errors we checked for there: https://github.com/PublicMapping/districtbuilder-classic/blob/develop/django/publicmapping/redistricting/tasks.py#L149
