### ISSUE TITLE
Error message and no Login / Registration buttons on Organization page

### ISSUE THREAD

**Issue by jfrankl** [PublicMapping/districtbuilder#651]
## Description
When a user is logged in but their login expires, navigating to an organization triggers and error and the user does not see a Login or Register button.

## Steps To Reproduce
1. Login
2. Wait 1 week, or update your JWT expiration here: https://github.com/PublicMapping/districtbuilder/blob/950253d514be74ba8c6edba4874fb1d1ce1c6173/docker-compose.yml#L28
3. Go to an organization page

## Expected behavior
I'd expect to not see an error and see a login and registration button in the top right menu

## Actual behavior
I do see an error and I don't see the login and registration

## Screenshots
![Screen Shot 2021-03-27 at 8 03 10 AM](https://user-images.githubusercontent.com/1809908/112720454-c983c880-8ed4-11eb-846c-5295b5602fab.png)

## Your environment
 - OS: macOS 11.2.1
 - Browser: Firefox
 - Version: 87.0

**Comment by maurizi** [comment]
@jfrankl I can't seem to reproduce this anymore.

**Comment by maurizi** [comment]
I _did_ just reproduce this on production, and I'm pretty sure how (but haven't tested this yet) - I think this state happens when you've been logged in but your JWT is expired.

**Comment by jfrankl** [comment]
That checks out with my experience.

**Comment by maurizi** [comment]
Description updated to reflect how to reproduce this.
