### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#663]
# Pre-deployment tasks
 - [x] Disable evaluate mode button
 - [x] Disable import button

# Post-deployment tasks
 - [x] Upload new Dane County region

**Comment by maurizi** [comment]
@tgilcrest We probably need to disable the Import button as well right? Without #629 we don't have really any error checking.

**Comment by tgilcrest** [comment]
Yes that's a great point. We should disable that for this release.
