### ISSUE TITLE
Add size control to paintbrush tool

### ISSUE THREAD

**Issue by tgilcrest** [PublicMapping/districtbuilder#742]
We want to add a size control to the paintbrush to make filling in larger areas easier.

[Wireframe here](https://share.goabstract.com/d1beff32-45f8-4987-af0f-840d97507d0b?mode=design&sha=09b392079f20d92a20fe38878b27420f0bd1e703)

**Note:** the wireframe differs from the AC. Implement what is described in the AC, but use the wireframe as a visual guide.

AC:
* When the user clicks on the paintbrush tool, an input range (slider) appears
* The slider is visible while the paintbrush tool is selected. It disappears when another tool is selected.
* Options should be 1, 2, 3, 4, 5 (there are five sizes/stops on the slider -- *this is different than the wireframe*)
* Option 1 should be the same size brush as is currently implemented
* 1 should be the default
* Each step should increase the brush size by a certain radius, up to some max

**Note:** It's not clear what the max size or size step should be. Feel free to experiment with sizing to see how it feels when implementing.

**Comment by pcaisse** [comment]
@jfrankl If the user uses the paintbrush tool and changes the size to, say, 5, and then switches to another tool and then selects the paintbrush tool again, should the brush size go back to the default of 1 or should it go back to whatever size they had selected before (5 in this example)?

**Comment by jfrankl** [comment]
Thanks for asking. It would be ideal for the size to persist.
