### ISSUE TITLE
Add cron job to check for unverified users and delete them periodically

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#77]

**Comment by hectcastro** [comment]
Just a heads up that this could end up becoming more convoluted than expected. We don't really have a good place to run a scheduled job like this per environment (unless we take a shortcut and use the Bastion).

In other containerized apps, we've used CloudWatch Events to schedule the invocation of ECS tasks within the existing ECS cluster.

**Comment by maurizi** [comment]
@hectcastro does it reduce the complexity if its acceptable to run it on all app servers at once?

**Comment by hectcastro** [comment]
Sorry for the delayed response here.

I don't think so. Within a given service instance running on Fargate, there really isn't a way to tap into OS level facilities like `cron`. In other containerized app setups, we've setup CloudWatch Event rules (which can be expressed as `cron` expressions) to fire off downstream actions (e.g., invoke a Lambda function, run an ECS task, etc.). I think we'd have to do something similar to achieve this functionality here:

- CloudWatch Event rules expression fires daily
- That kicks off a management command-like ECS task that's run within the ECS cluster and does the necessary database grooming

**Comment by dmcglone** [comment]
Closed, but we should figure out how to handle unverified accounts
