### ISSUE TITLE
Rename project to DistrictBuilder

### ISSUE THREAD

**Issue by ColeKettler** [PublicMapping/districtbuilder#78]
We should consider referring to this project as DistrictBuilder and changing the name of the older version of this application to DistrictBuilder Classic. GitHub repositories will need to be renamed, references in documentation will need to be updated, and AWS resources will need to be cleaned up.

**Comment by jfrankl** [comment]
@tgilcrest looks good to me

**Comment by kshepard** [comment]
Also looks good to me.
