### ISSUE TITLE
Keyboard shortcuts should not fire while user renames map

### ISSUE THREAD

**Issue by jfrankl** [PublicMapping/districtbuilder#792]
While typing in the input field to rename a map, keyboard shortcuts continue to fire. For shortcuts, we should ignore input while a text input is focused.

![Screen Shot 2021-05-26 at 1 36 13 PM](https://user-images.githubusercontent.com/1809908/119705937-58ef1e80-be27-11eb-9bc9-1440f8c0f396.png)

**Comment by maurizi** [comment]
We should be able to fix this in a generic fashion by checking what the currently focused element and not firing a shortcut if it is an `<input>`, `<select>`, `<textarea>` https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement
