### ISSUE TITLE
Reduce space under Organization picker in New Map workflow

### ISSUE THREAD

**Issue by jfrankl** [PublicMapping/districtbuilder#803]
The Organization picker has more space under it than the other sections of the New Map workflow. Reduce the amount of space to match the other sections.

![Screen Shot 2021-06-02 at 10 14 33 PM](https://user-images.githubusercontent.com/1809908/120576428-bddee180-c3f0-11eb-937b-7bb548468364.png)

**Comment by dmcglone** [comment]
We did this
