### ISSUE TITLE
Rephrase helper text for "Population deviation tolerance"

### ISSUE THREAD

**Issue by jfrankl** [PublicMapping/districtbuilder#804]
In the New Map workflow, I find that the helper text for "Population deviation tolerance" does not provide enough support for a new user. It currently reads:

> Depending on whether you are making a map for learning purposes or are trying to make the exercise as realistic as possible

This seems like an incomplete thought. It tells me that this number has something to do with how detailed the map will be, but it doesn't give any advice for how I should set the value. Is a higher or lower number good for learning purposes?

I propose something like:

> How detailed of a map do you want to draw? We recommend using 5–10% for learning purposes, 1–4% for a realistic map, or 0% for a legally viable map.

@tgilcrest what do you think? I made up those ranges—do they check out to you?

**Comment by tgilcrest** [comment]
Well actually it's just US Congressional maps that require 0% deviation (and occasionally it's not required if you're balancing it with other criteria). Also, state house and senate plans typically have a little more population flexibility, in the 5-10% range.

Do you think it's important to explain this?

> How balanced do you want your districts' population to be? Congressional maps require 0% to be legally valid, but state maps can fall within 5-10%. 

But this doesn't get at the "being more precise is more advanced" message that also seems important.

 --------------
 
Or here's an idea: maybe we could possibly suggest a "recommended deviation" for each chamber somehow, that could communicate there are different levels of deviation for the different levels of gov't.

![image](https://user-images.githubusercontent.com/14098314/120672988-c8d15a80-c460-11eb-9883-dbcc7eeceb28.png)

**Comment by jfrankl** [comment]
Good point that the connection is more nuanced and depends on the chamber. I think for the short term we should avoid the more difficult problem of doing a recommended deviation, based on the type of map they are drawing, and focus on communicating more clearly about the "Lower numbers are more detailed" concept and here's what we recommend.

Thoughts on this variation?

> How detailed of a map do you want to draw? Setting a lower tolerance means the population of your districts will need to be more exact. If you aren't sure, we think 5% is a good starting point.

**Comment by tgilcrest** [comment]
Thanks, that makes sense. Sounds good to me.
