### ISSUE TITLE
Add shortText and longText for Competitiveness metric

### ISSUE THREAD

**Issue by kevinearldenny** [PublicMapping/districtbuilder#843]
## Detailed Description
We need an explanatory `shortText` for the `ProjectEvaluateSummary` page as well as a `longText` to live on the Competitiveness detail page. There are a few dev cards related to this page in flight currently, but once we have this copy written it should be very easy to add it in to the application.

**Comment by dmcglone** [comment]
Short text:
A competitiveness metric evaluates the plan based on the average partisan lean of each district.

Long text:
A competitiveness metric evaluates the plan based on the average partisan lean of each district, calculated using the Partisan Voting Index (PVI). A partisan lean of the district plan which deviates from the overall lean of the state can be indicative of gerrymandering.

**Comment by maurizi** [comment]
This is done now
