### ISSUE TITLE
Request entity too large when importing block equivalency file csv

### ISSUE THREAD

**Issue by dmcglone** [PublicMapping/districtbuilder#846]
## Description
When attempting to import a district index file csv into DistrictBuilder, the webpage doesn't respond after loading the data and clicking "Create map". We've identified an error in Rollbar that is `PayloadTooLargeError: request entity too large`.  This was tested in New Jersey and Pennsylvania with Congressional Block Equivency files.

## Steps To Reproduce

1. Go to 'Import page'
2. Click on 'Browse files, select file'
3. Enter the number of districts
4. Click 'Create map'. No response.

## Sample NJ file attached
[nj_congress_bef.zip](https://github.com/PublicMapping/districtbuilder/files/6804154/nj_congress_bef.zip)

**Comment by kevinearldenny** [comment]
@dmcglone Were you getting a message about an excessive number of flagged rows when trying your import? Weirdly, I'm seeing this on staging: 
![image](https://user-images.githubusercontent.com/66973361/125356842-c5b96c00-e334-11eb-9e86-0e9d0db13c84.png)

But when I try locally, I'm not getting any flagged rows:
![image](https://user-images.githubusercontent.com/66973361/125356902-db2e9600-e334-11eb-847c-ad3cf100644d.png)

Not sure what could be causing this, but seems like this might be pointing us in the right direction

**Comment by dmcglone** [comment]
@kevinearldenny Okay, I compared the 2010 and 2020 block geometries to the BEF in question. It looks like BEF for NJ is using the _2020 blocks_ which is probably the reason for the excessive number of flags. Perhaps locally you are now running off the 2020 data which is the reason for the lack of flags on your end?

If indeed a large number of flags is causing it to break, we probably need some additional messaging on this page about which version of BEF should be used on import.

**Comment by dmcglone** [comment]
https://rollbar.com/Azavea/DistrictBuilder/items/42/
