### ISSUE TITLE
Add demographic labels to vector tiles

### ISSUE THREAD

**Issue by kshepard** [PublicMapping/districtbuilder#86]
## Overview

The prototype has demographic labels integrated into the vector tiles. These take the form of compact, human-readable counts, e.g. 2.7K for population. See the following script to see how it was done in the prototype:

https://github.com/azavea/districtbuilder-2/blob/486e50d974cc61d77b939b765ad1ed4de454c8b6/public/process/process.sh#L23

## Acceptance criteria

Vector tiles are baked out with demographic labels

**Comment by jfrankl** [comment]
One update to the script Kenny referenced. When using `geojson-polygon-labels`, include the `--style largest` flag. This will make sure each geounit only has one label. In my script, which did not include that flag, a multipolygon geounit could have multiple labels, which looks confusing.
