### ISSUE TITLE
Deleted maps still display on Organization admin page

### ISSUE THREAD

**Issue by dmcglone** [PublicMapping/districtbuilder#881]
After a user deletes a map, the map is still listed on the Organization admin page. When the admin clicks on the URL for the deleted map, they get a Page Not Found error. The map should no longer be listed as an option to Feature.

**Comment by maurizi** [comment]
@dmcglone I'm not able to replicate this bug on staging - was this on production?

**Comment by dmcglone** [comment]
@maurizi yes this is on production

**Comment by maurizi** [comment]
This was fixed in https://github.com/PublicMapping/districtbuilder/pull/805
