### ISSUE TITLE
Import CSV page errors

### ISSUE THREAD

**Issue by dmcglone** [PublicMapping/districtbuilder#945]
When attempting to import a CSV block equivalency file, I'm running into everything from general slowness to unresponsive behavior at various steps. It generally seems to be happening more often with state lower files, which do have a larger number of districts. 

Three types of unresponsive behavior:

- When importing the Florida Lower CSV, the page got stuck in the Upload step.
- When importing the Pennsylvania Lower CSV, the CSV was able to import but it got stuck on the Create Map step.
- When importing a Pennsylvania Congress CSV, the page was stuck on Create Map but later after navigating away from the page it did actually create the map.

[fl_lower.csv](https://github.com/PublicMapping/districtbuilder/files/7000507/fl_lower.csv)
[pa_lower.csv](https://github.com/PublicMapping/districtbuilder/files/7000509/pa_lower.csv)

**Comment by maurizi** [comment]
Looks like the accompanying Rollbar error for this is https://rollbar.com/Azavea/DistrictBuilder/items/42/

**Comment by maurizi** [comment]
Potential fix: https://stackoverflow.com/questions/52783959/nest-js-request-entity-too-large-payloadtoolargeerror-request-entity-too-larg

**Comment by maurizi** [comment]
I suspect this also has the same root cause as #618
