### ISSUE TITLE
Alaska zooms to northern Europe

### ISSUE THREAD

**Issue by ddohler** [PublicMapping/districtbuilder#953]
## Description
Creating a new map with Alaska initially zooms the map to Iceland

## Steps To Reproduce
1. Create a new map from Alaska

## Expected behavior
The map should zoom to Alaska initially.

## Actual behavior
The map zooms to Iceland.

## Your environment
MacOS, Firefox

## Additional context
Part of the Aleutian Island chain crosses the anti-meridian, and we've discovered issues on other projects with Mapbox GL and setting the map view when part of the bounding box crosses the anti-meridian, so I suspect something similar is happening here.

**Comment by maurizi** [comment]
We fixed this manually for the 2010 version of Alaska, so it should be relatively simple to reapply the same fix to the 2020 version.

**Comment by maurizi** [comment]
I updated the `static-metadata.json` for both staging & production to set their `bbox` to `[-170, 50, -140, 72]`, which matches what we were using for the 2010 region.
