### ISSUE TITLE
Make Reference Layer load by default within Project Template

### ISSUE THREAD

**Issue by dmcglone** [PublicMapping/districtbuilder#955]
As a bonus for Organizational accounts and feature requested from a client. We should have the ability to make a reference layer load by default within a project template. Existing reference layer functionality still available within the project once copied to their account from a template.

AC:
 - Projects created from templates should copy reference layers from the template, if any are specified

**Comment by maurizi** [comment]
> We should have the ability to make a reference layer load by default within a project template

@dmcglone does this mean they need to be visible by default when the map is loaded, or merely already exist as a reference layer (but you need to click the checkbox to show it)?

I believe the behavior we talked about for reference layers in general was they were not visible by default when the map first loads.

**Comment by dmcglone** [comment]
Already exist as a layer in the project but is not visible by default, and the user would need to click the checkbox to view it would be adequate
