### ISSUE TITLE
PG sessions blocking in idle state waiting on ClientRead

### ISSUE THREAD

**Issue by rbreslow** [PublicMapping/districtbuilder#960]
TBD.

**Comment by maurizi** [comment]
After some trial and error, I think I've identified the issue in question causing this error - we're blocking the event loop when running the TopoJSON mergeArcs function (or other CPU intensive things like imports / exports).

Using the load testing script in https://github.com/PublicMapping/districtbuilder/pull/1046 I was able to recreate the idle transaction / slow to respond health checks and cause the staging site to temporarily 504.

By switching the merge function to a worker thread pool (https://github.com/PublicMapping/districtbuilder/commit/c214bac64111615e7a213972d512a7d765c68821) I was able to increase throughput & completely reduce the slowness in the healthcheck endpoint. Unfortunately we can't use that branch as-is (it takes far too long to run `deserialize` for large regions) but this is a great starting point to work from.

**Comment by rbreslow** [comment]
I thought I'd share the query that I initially used to determine that sessions were idle (`state_change`) waiting on ClientRead (`wait_event`). I'm not sure if I left it anywhere, but it seems appropriate to keep it in this issue.

```sql
SELECT client_addr,
    query_start,
    state_change,
    wait_event,
    EXTRACT(epoch FROM (current_timestamp - query_start)) AS duration,
    query
FROM pg_stat_activity
WHERE wait_event IS NOT NULL
    AND backend_type = 'client backend'
	AND query = 'SELECT 1';
```

Awesome! I'm so happy that the load testing yielded fruit. I'm also excited to hear whether or not you can scale down the application now and if you continue any exploration into the data loading at startup.
