### ISSUE TITLE
Visualize all of the performance issues we're experiencing

### ISSUE THREAD

**Issue by rbreslow** [PublicMapping/districtbuilder#962]
@colekettler and I are going to meet to create a visualization of all of the various performance issues we're experiencing and try to figure out how they fit together. Afterward, prioritize and determine a path forward.

e.g.:

- #960 
- Super long application start up times
- Health check thresholds are raised so much health checks are almost useless
- Discussions around data partitioning
- How can we eventually get back to lower memory usage and Fargate? Is it even possible with the amount of `mmap`'d objects?
- ...

**Comment by rbreslow** [comment]
![DistrictBuilder Performance Issues](https://user-images.githubusercontent.com/1774125/130648257-679377d4-80a3-4a4f-b29c-0759576f9f5b.jpg)

https://miro.com/welcomeonboard/aHJHbU02VTlzYjNhWHZVanJMV245Vkl3R0FDTHZGcE1oMlZDRlc1djFYQnM0UlFvRnZsVWdGMzdDWm5KWVhod3wzMDc0NDU3MzU1MDQ4NTQ4NzQ4

**Comment by colekettler** [comment]
Meeting has been scheduled, moving this to done.
