### ISSUE TITLE
Update PVI calculation

### ISSUE THREAD

**Issue by maurizi** [PublicMapping/districtbuilder#970]
We should not be including other party votes when calculating PVI, only Dem / Rep:
https://github.com/PublicMapping/districtbuilder/blob/2a76d57e5e424df52c033fa9f57ecdd83921972d/src/client/functions.ts#L124-L131

**Comment by dmcglone** [comment]
Here's an excel calculator from DailyKos that explains the correct way to calculate PVI over two elections:
https://drive.google.com/file/d/0B_nTSADXKM04cVlEUU5DMllqc0U/edit?usp=sharing
