### ISSUE TITLE
Allow admin users to set project template from project

### ISSUE THREAD

**Issue by dmcglone** [PublicMapping/districtbuilder#997]
Project templates are kind of a pain to make right now because it's a manual process of adding the data and copying the district_definition from an existing project. To make that easier for me, and also enable Organization admins to do it, there should be an option for admins to _convert_ or _set_ a Project as a Project Template.

This should be available via a button on the Organization admin page, similar to the Feature button. It may seem counterintuitive to list "Template" as a field here, but it will be blank, this will almost always be a plan that is Imported from CSV.
![image](https://user-images.githubusercontent.com/1688859/132046192-3fb39620-9c55-4970-8c0c-24c5d89de167.png)

The button would create a new row in the project_template table, copying over the details from the project (chamber, district_definition, region). To enable Organization admins to add a description, we would probably need another admin page, or perhaps a table below the map list, that enables admins to add/edit metadata for the templates.

**Comment by maurizi** [comment]
👍 

This would be better as an option on the project flyout menu on the home screen - probably open a modal and allow you to choose which organization you want to make a template for.

If we put it on the org. admin screen it would be a chicken/egg problem, as the maps shown there only those with a project template for the organization.
